### ISSUE TITLE
ERROR: relation "migration_model" does not exist

### ISSUE THREAD

**Issue by tepene** [keycloak/keycloak#10235]
### Describe the bug

I'm not 100% sure if this is a bug or a missing configuration from my side. I can't get the latest Docker image `quay.io/keycloak/keycloak:17.0.0` up and running. The start always fails with the follwoing log messages:

```
2022-02-15 19:54:42,453 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 42P01
2022-02-15 19:54:42,453 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) ERROR: relation "migration_model" does not exist
  Position: 121
2022-02-15 19:54:42,500 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-02-15 19:54:42,555 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-02-15 19:54:42,555 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
2022-02-15 19:54:42,555 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: could not extract ResultSet
2022-02-15 19:54:42,556 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: relation "migration_model" does not exist
  Position: 121
```
Anyone experiencing the same issue?  The configuration was working with the `jboss/keycloak:16.1.0` image. I also tried to delete and re-create an empty database schema. But no luck either.

### Version

17.0.0

### Expected behavior

successfull start.

### Actual behavior

`ERROR: ERROR: relation "migration_model" does not exist`

### How to Reproduce?

```yaml
# docker-compose.yml
version: "3.6"
services:
  ## Keycloak IAM Authentication Provider
  authentication-provider:
    image: quay.io/keycloak/keycloak:17.0.0
    command: "start --auto-build"
    ports:
      - "9001:8080"
    restart: unless-stopped
    environment:
      ## Host settings
      KC_HOSTNAME: keycloak
      ## Database settings
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DB}
      KC_DB_SCHEMA: ${KEYCLOAK_SCHEMA}
      KC_DB_USERNAME: ${PG_USER}
      KC_DB_PASSWORD: ${PG_PASSWORD}
      ## Admin User settings
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      ## Proxy settings
      KC_PROXY: edge

### Anything else?

_No response_

**Comment by jokyboy25** [comment]
Got the same error migrating our keycloak server from 9.0.2 to 17.0.0

I notice that @tepene override the db-schema as we do. So maybe this issue is related to overriding db-schema.

When I looked to the Stack trace, I found that the error was thrown when keycloak is using a @NamedQuery. Maybe in that case the custom schema is not defined correctly. 


`Error details:: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)
        at org.hibernate.query.Query.getResultList(Query.java:165)
        at org.keycloak.models.jpa.MigrationModelAdapter.init(MigrationModelAdapter.java:59)
        at org.keycloak.models.jpa.MigrationModelAdapter.<init>(MigrationModelAdapter.java:42)
        at org.keycloak.models.jpa.JpaRealmProvider.getMigrationModel(JpaRealmProvider.java:93)
        at org.keycloak.migration.MigrationModelManager.migrate(MigrationModelManager.java:105)
        at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.migrateModel(QuarkusJpaConnectionProviderFactory.java:293)
        at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.initSchema(QuarkusJpaConnectionProviderFactory.java:218)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
        at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:158)
        at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:96)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.initializeKeycloakSessionFactory(QuarkusKeycloakApplication.java:75)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:56)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_8292a286c9778cb4a07bc3314fcbfb61e7fe81a0.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:84)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:34)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:84)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:79)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2322)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2075)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
        at org.hibernate.loader.Loader.doQuery(Loader.java:956)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
        at org.hibernate.loader.Loader.doList(Loader.java:2868)
        at org.hibernate.loader.Loader.doList(Loader.java:2850)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
        at org.hibernate.loader.Loader.list(Loader.java:2677)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1454)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
        ... 43 more
Caused by: org.postgresql.util.PSQLException: ERREUR: la relation « migration_model » n'existe pas
  Position : 121
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
        at com.sun.proxy.$Proxy90.executeQuery(Unknown Source)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeQuery(PreparedStatementWrapper.java:78)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
        ... 58 more
`

**Comment by svkoblov** [comment]
Yes, we are using custom DB schema as well.
When I remove the 'db-schema' parameter from config file or startup keys - it launches a new installation of Keycloak in 'public' schema (we use PostgreSQL). 
Will try to copy our DB between schemas and place it into a public to see if that helps

**Comment by Luthien-in-edhil** [comment]
+1 

Running into this issue when doing a first test with Keycloak 17.0.0 on Quarkus on a local machine:
-  PostgreSQL v12
-  custom schema set in keycloak.conf: `db-schema=keycloak17 `
- the schema contains a copy of the DB of a (working) Keycloak v.16.1.0 instance

```
bin/kc.sh build
Updating the configuration and installing your custom providers, if any. Please wait.
2022-02-28 16:23:46,426 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 7304ms
```

```
bin/kc.sh show-config
Current Mode: none
Runtime Configuration:
	kc.cache =  local (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.config.args =  show-config (SysPropConfigSource)
	kc.db =  postgres (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.db-password =  ******* (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.db-schema =  keycloak17 (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.db-url-database =  localdb (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.db-url-host =  localhost (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.db-username =  dbuser (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.home.dir =  bin/../ (SysPropConfigSource)
	kc.http-enabled =  true (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.http-relative-path =  /auth (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.metrics-enabled =  true (PropertiesConfigSource[source=file:/Applications/keycloak-17.0.0-quarkus/bin/../conf/keycloak.conf])
	kc.quarkus-properties-enabled =  false (PersistedConfigSource)
	kc.show.config =  none (SysPropConfigSource)
	kc.version =  17.0.0 (SysPropConfigSource)
```

```
> bin/kc.sh start-dev
Updating the configuration and installing your custom providers, if any. Please wait.
2022-02-28 16:24:43,699 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 7444ms
2022-02-28 16:24:48,624 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>
2022-02-28 16:24:49,477 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-02-28 16:24:49,583 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-02-28 16:24:49,663 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-02-28 16:24:50,022 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.5.Final
2022-02-28 16:24:50,806 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_114278, Site name: null
2022-02-28 16:24:52,551 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 42P01
2022-02-28 16:24:52,552 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) ERROR: relation "migration_model" does not exist
  Position: 121
2022-02-28 16:24:52,719 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2022-02-28 16:24:52,719 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
2022-02-28 16:24:52,720 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: could not extract ResultSet
2022-02-28 16:24:52,720 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: relation "migration_model" does not exist
  Position: 121
2022-02-28 16:24:52,720 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

**Comment by starmage** [comment]
Same issue, also with a custom DB schema.

**Comment by fraiguana** [comment]
Same issue for me but only when i try to connect to postgresql on Azure , locally works fine.
I Resolved it (workaround) by specifying schema name inside KC_DB_SCHEMA and also in KC_DB_URL

ENV KC_DB_URL=jdbc:postgresql://[db_addr]:[db_port]/[db_name]?currentSchema=[db_schema]

**Comment by Xerkus** [comment]
Just encountered the same error after I changed from `--db-url` to using separate env variables on 17.0.0 -> 17.0.0.

I kept this workaround since keycloak-x16:
```
KC_DB_URL_HOST=
KC_DB_URL_DATABASE=
KC_DB_SCHEMA=
```
```bash
 kc.sh start --db-url="jdbc:postgresql://${KC_DB_URL_HOST}/${KC_DB_URL_DATABASE}?currentSchema=${KC_DB_SCHEMA}"
```
It works because kc.sh in docker evaluates variables 
 
This issue should have been fixed, I think?
https://github.com/keycloak/keycloak/issues/9398
https://github.com/keycloak/keycloak/issues/9328

**Comment by Schwaller** [comment]
We don't specify anything about the schema but now upgrading to 17.0.0 or 17.0.1 the server won't start using the old postgres DB. It seems to try to create the master realm although it already exists and fails doing so. 
'''
2022-04-08T14:55:57.894778100Z Changes detected in configuration. Updating the server image.
2022-04-08T14:55:57.899738800Z Updating the configuration and installing your custom providers, if any. Please wait.
2022-04-08T14:56:04.497630400Z 2022-04-08 16:56:04,496 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 5386ms
2022-04-08T14:56:04.517219900Z Server configuration updated and persisted. Run the following command to review the configuration:
2022-04-08T14:56:04.517243800Z 
2022-04-08T14:56:04.517775900Z 	kc.sh show-config
2022-04-08T14:56:04.517786400Z 
2022-04-08T14:56:04.518825400Z Next time you run the server, just run:
2022-04-08T14:56:04.518834200Z 
2022-04-08T14:56:04.518836600Z 	kc.sh start --spi-connections-jpa-default-migration-strategy=manual
2022-04-08T14:56:04.518838400Z 
2022-04-08T14:56:06.718526300Z 2022-04-08 16:56:06,716 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: localhost:8081, Strict HTTPS: true, Path: <request>, Strict BackChannel: true, Admin: <request>, Port: -1, Proxied: true
2022-04-08T14:56:07.453530800Z 2022-04-08 16:56:07,452 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-04-08T14:56:07.462908600Z 2022-04-08 16:56:07,462 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-04-08T14:56:07.488412900Z 2022-04-08 16:56:07,487 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-04-08T14:56:07.671287800Z 2022-04-08 16:56:07,670 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.6.Final
2022-04-08T14:56:07.759361400Z 2022-04-08 16:56:07,758 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-04-08T14:56:07.759532200Z 2022-04-08 16:56:07,759 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2022-04-08T14:56:07.816565100Z 2022-04-08 16:56:07,816 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-04-08T14:56:07.816764300Z 2022-04-08 16:56:07,816 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2022-04-08T14:56:07.816900300Z 2022-04-08 16:56:07,816 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-04-08T14:56:07.817146300Z 2022-04-08 16:56:07,816 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2022-04-08T14:56:09.826247600Z 2022-04-08 16:56:09,825 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 14a4c50f97f7-65397: no members discovered after 2003 ms: creating cluster as coordinator
2022-04-08T14:56:09.834471800Z 2022-04-08 16:56:09,834 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [14a4c50f97f7-65397|0] (1) [14a4c50f97f7-65397]
2022-04-08T14:56:09.838406000Z 2022-04-08 16:56:09,837 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `14a4c50f97f7-65397`, physical addresses are `[172.24.0.14:50127]`
2022-04-08T14:56:10.280661500Z 2022-04-08 16:56:10,279 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 14a4c50f97f7-65397, Site name: null
2022-04-08T14:56:11.559493900Z 2022-04-08 16:56:11,559 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2022-04-08T14:56:11.606636800Z 2022-04-08 16:56:11,606 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 23505
2022-04-08T14:56:11.606779200Z 2022-04-08 16:56:11,606 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) ERROR: duplicate key value violates unique constraint "constraint_9"
2022-04-08T14:56:11.606815100Z   Detail: Key (name, realm_id)=(_browser_header.contentSecurityPolicyReportOnly, master) already exists.
2022-04-08T14:56:11.608713700Z 2022-04-08 16:56:11,608 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (main) HHH000010: On release of batch it still contained JDBC statements
2022-04-08T14:56:11.667817300Z 2022-04-08 16:56:11,667 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-04-08T14:56:11.846900800Z 2022-04-08 16:56:11,846 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-04-08T14:56:11.848585300Z 2022-04-08 16:56:11,846 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: org.keycloak.models.ModelDuplicateException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
2022-04-08T14:56:11.848626000Z 	at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:80)
2022-04-08T14:56:11.848632600Z 	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
2022-04-08T14:56:11.848635000Z 	at com.sun.proxy.$Proxy83.flush(Unknown Source)
2022-04-08T14:56:11.848636900Z 	at org.keycloak.models.jpa.RealmAdapter.setSslRequired(RealmAdapter.java:125)
2022-04-08T14:56:11.848638700Z 	at org.keycloak.services.managers.RealmManager.setupRealmDefaults(RealmManager.java:247)
2022-04-08T14:56:11.848640500Z 	at org.keycloak.services.managers.RealmManager.createRealm(RealmManager.java:111)
2022-04-08T14:56:11.848642200Z 	at org.keycloak.services.managers.ApplianceBootstrap.createMasterRealm(ApplianceBootstrap.java:67)
2022-04-08T14:56:11.848644100Z 	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.createMasterRealm(QuarkusJpaConnectionProviderFactory.java:239)
2022-04-08T14:56:11.848645900Z 	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.initSchema(QuarkusJpaConnectionProviderFactory.java:199)
2022-04-08T14:56:11.848656700Z 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
2022-04-08T14:56:11.848658700Z 	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:136)
2022-04-08T14:56:11.848660500Z 	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:96)
2022-04-08T14:56:11.848662200Z 	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.initializeKeycloakSessionFactory(QuarkusKeycloakApplication.java:68)
2022-04-08T14:56:11.848664000Z 	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:49)
2022-04-08T14:56:11.848665800Z 	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
2022-04-08T14:56:11.848668300Z 	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
2022-04-08T14:56:11.848670600Z 	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
2022-04-08T14:56:11.848672400Z 	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
2022-04-08T14:56:11.848674100Z 	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
2022-04-08T14:56:11.848675800Z 	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
2022-04-08T14:56:11.848677500Z 	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
2022-04-08T14:56:11.848679200Z 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
2022-04-08T14:56:11.848680900Z 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
2022-04-08T14:56:11.848682800Z 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2022-04-08T14:56:11.848684600Z 	at io.quarkus.runtime.Application.start(Application.java:101)
2022-04-08T14:56:11.848686400Z 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
2022-04-08T14:56:11.848688200Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
2022-04-08T14:56:11.848689900Z 	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:86)
2022-04-08T14:56:11.848691500Z 	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:34)
2022-04-08T14:56:11.848693300Z 	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
2022-04-08T14:56:11.848694900Z 	at picocli.CommandLine.access$1300(CommandLine.java:145)
2022-04-08T14:56:11.848696800Z 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
2022-04-08T14:56:11.848698600Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
2022-04-08T14:56:11.848700400Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
2022-04-08T14:56:11.848704100Z 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
2022-04-08T14:56:11.848705900Z 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
2022-04-08T14:56:11.848707900Z 	at picocli.CommandLine.execute(CommandLine.java:2078)
2022-04-08T14:56:11.848709700Z 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:84)
2022-04-08T14:56:11.848711400Z 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:77)
2022-04-08T14:56:11.848713200Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-08T14:56:11.848715100Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-08T14:56:11.848717600Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-08T14:56:11.848719800Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-04-08T14:56:11.848721800Z 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
2022-04-08T14:56:11.848723400Z 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
2022-04-08T14:56:11.848725200Z Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
2022-04-08T14:56:11.848727000Z 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
2022-04-08T14:56:11.848728900Z 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
2022-04-08T14:56:11.848730700Z 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
2022-04-08T14:56:11.848732500Z 	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1406)
2022-04-08T14:56:11.848734300Z 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1389)
2022-04-08T14:56:11.848736000Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-08T14:56:11.848737700Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-08T14:56:11.848739400Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-08T14:56:11.848741100Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-04-08T14:56:11.848743000Z 	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:60)
2022-04-08T14:56:11.848744900Z 	... 43 more
2022-04-08T14:56:11.848746700Z Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
2022-04-08T14:56:11.848748700Z 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109)
2022-04-08T14:56:11.848750400Z 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
2022-04-08T14:56:11.848754300Z 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
2022-04-08T14:56:11.848756200Z 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
2022-04-08T14:56:11.848757900Z 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
2022-04-08T14:56:11.848759800Z 	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
2022-04-08T14:56:11.848762100Z 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3375)
2022-04-08T14:56:11.848764100Z 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3908)
2022-04-08T14:56:11.848765900Z 	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
2022-04-08T14:56:11.848767600Z 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
2022-04-08T14:56:11.848769300Z 	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
2022-04-08T14:56:11.848771000Z 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
2022-04-08T14:56:11.848772600Z 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
2022-04-08T14:56:11.848774500Z 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
2022-04-08T14:56:11.848776300Z 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
2022-04-08T14:56:11.848778200Z 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
2022-04-08T14:56:11.848780000Z 	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1402)
2022-04-08T14:56:11.848781700Z 	... 49 more
2022-04-08T14:56:11.848783400Z Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "constraint_9"
2022-04-08T14:56:11.848785200Z   Detail: Key (name, realm_id)=(_browser_header.contentSecurityPolicyReportOnly, master) already exists.
2022-04-08T14:56:11.848787000Z 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
2022-04-08T14:56:11.848788900Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
2022-04-08T14:56:11.848790700Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
2022-04-08T14:56:11.848792600Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
2022-04-08T14:56:11.848794400Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
2022-04-08T14:56:11.848796000Z 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
2022-04-08T14:56:11.848797700Z 	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:134)
2022-04-08T14:56:11.848801100Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-08T14:56:11.848802800Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-08T14:56:11.848805100Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-08T14:56:11.848807100Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-04-08T14:56:11.848808800Z 	at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
2022-04-08T14:56:11.848810600Z 	at com.sun.proxy.$Proxy90.executeUpdate(Unknown Source)
2022-04-08T14:56:11.848812300Z 	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
2022-04-08T14:56:11.848814000Z 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
2022-04-08T14:56:11.848815700Z 	... 61 more
2022-04-08T14:56:11.848817200Z  '''

**Comment by Schwaller** [comment]
Is anybody able to migrate a Keycloak 16.x.x to Keycloak 17.0.1 without deleting the Postgres DB? Some help would be greatly appreciated!

**Comment by starmage** [comment]
We managed to do that. The only issues we had was because we were running with a custom schema, we had to use this form of the DB url
KC_DB_URL=jdbc:postgresql://host.name:5432/keycloak?currentSchema=custom_schema

Thanks to https://github.com/keycloak/keycloak/issues/10235#issuecomment-1065435988 and other posts on here.

**Comment by Schwaller** [comment]
Thank you for that input!
I will double check if setting the full KC_DB_URL instead of using KC_DB_URL_HOST, KC_DB_URL_PORT, KC_DB_URL_DATABASE etc. helps.

**Comment by DGuhr** [comment]
@pedroigor I just stumbled over this myself. Wdyt, should we add `?currentSchema={kc.db-schema:public}` to the [database wrapper](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/Database.java#L136)? Now that I look at it, are we missing a `?` between database and the properties part or is this by design and you should add the ? yourself bc. there are other properties without it? Not sure, tbh.

**Comment by daurrutia** [comment]
I'm seeing this in version 18, but Keycloak _does_ start. Is this expected?

```
postgres_1  | 2022-07-22 20:33:19.521 UTC [69] ERROR:  relation "migration_model" does not exist at character 25
postgres_1  | 2022-07-22 20:33:19.521 UTC [69] STATEMENT:  SELECT ID, VERSION FROM MIGRATION_MODEL ORDER BY UPDATE_TIME DESC
postgres_1  | 2022-07-22 20:33:20.604 UTC [69] ERROR:  relation "public.databasechangelog" does not exist at character 22
postgres_1  | 2022-07-22 20:33:20.604 UTC [69] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
postgres_1  | 2022-07-22 20:33:21.358 UTC [70] ERROR:  relation "public.databasechangeloglock" does not exist at character 22
postgres_1  | 2022-07-22 20:33:21.358 UTC [70] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock
postgres_1  | 2022-07-22 20:33:21.399 UTC [69] ERROR:  relation "public.databasechangelog" does not exist at character 22
postgres_1  | 2022-07-22 20:33:21.399 UTC [69] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
```

**Comment by YevheniiPokhvalii** [comment]
> I'm seeing this in version 18, but Keycloak _does_ start. Is this expected?
> 
> ```
> postgres_1  | 2022-07-22 20:33:19.521 UTC [69] ERROR:  relation "migration_model" does not exist at character 25
> postgres_1  | 2022-07-22 20:33:19.521 UTC [69] STATEMENT:  SELECT ID, VERSION FROM MIGRATION_MODEL ORDER BY UPDATE_TIME DESC
> postgres_1  | 2022-07-22 20:33:20.604 UTC [69] ERROR:  relation "public.databasechangelog" does not exist at character 22
> postgres_1  | 2022-07-22 20:33:20.604 UTC [69] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
> postgres_1  | 2022-07-22 20:33:21.358 UTC [70] ERROR:  relation "public.databasechangeloglock" does not exist at character 22
> postgres_1  | 2022-07-22 20:33:21.358 UTC [70] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock
> postgres_1  | 2022-07-22 20:33:21.399 UTC [69] ERROR:  relation "public.databasechangelog" does not exist at character 22
> postgres_1  | 2022-07-22 20:33:21.399 UTC [69] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
> ```

The same here. Just installed Keycloak v19 with PostgreSQL v.14.4.0.
 We did not have this error when using Keycloak 17.

**Comment by pedroigor** [comment]
It should be related to https://github.com/keycloak/keycloak/pull/13399.

It was fixed in v19.0.1.

**Comment by YevheniiPokhvalii** [comment]
> It should be related to #13399.
> 
> It was fixed in v19.0.1.

My Keycloak version is 19.0.1
Moreover, if I log into a database pod, I can run all those commands without any errors:
```
keycloak=> SELECT ID, VERSION FROM MIGRATION_MODEL ORDER BY UPDATE_TIME DESC;
  id   | version
-------+---------
 r6f3m | 19.0.1
(1 row)

keycloak=> SELECT COUNT(*) FROM public.databasechangelog;
 count
-------
   107
(1 row)

keycloak=> SELECT COUNT(*) FROM public.databasechangeloglock;
 count
-------
     3
(1 row)

keycloak=>
```

**Comment by YevheniiPokhvalii** [comment]
I guess, I'll create a new issue.

**Comment by RossComputerGuy** [comment]
I'm currently experiencing this issue, restarted the pod and it still isn't working. Oddly enough, this issue goes away when using Minikube on Linux instead of macOS. Same setup on both machines.

**Comment by pedroigor** [comment]
@RossComputerGuy @YevheniiPokhvalii Any chance I can reproduce this locally? AFAIK, the original issue was related to issues when recognizing a custom schema when using `db-url-database`. Is this still the case?

**Comment by RossComputerGuy** [comment]
The issue miraculously disappeared.

**Comment by jamesdh** [comment]
I pushed an example to https://github.com/jamesdh/keycloak_startup containing a simple docker-compose that starts up Postgres and keycloak. If you simple run `docker compose up` you'll eventually see the logs spit out the following: 

```
postgres  | 2023-06-29 15:58:24.897 UTC [68] ERROR:  relation "migration_model" does not exist at character 25
postgres  | 2023-06-29 15:58:24.897 UTC [68] STATEMENT:  SELECT ID, VERSION FROM MIGRATION_MODEL ORDER BY UPDATE_TIME DESC
postgres  | 2023-06-29 15:58:25.249 UTC [68] ERROR:  relation "public.databasechangelog" does not exist at character 22
postgres  | 2023-06-29 15:58:25.249 UTC [68] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
postgres  | 2023-06-29 15:58:25.450 UTC [69] ERROR:  relation "public.databasechangeloglock" does not exist at character 22
postgres  | 2023-06-29 15:58:25.450 UTC [69] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock
postgres  | 2023-06-29 15:58:25.468 UTC [68] ERROR:  relation "public.databasechangelog" does not exist at character 22
postgres  | 2023-06-29 15:58:25.468 UTC [68] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
```

**Comment by phebing** [comment]
We also stumbled accross this using the same scenario as @jamesdh but with Keycloak 20.0.
I did a little digging and the tables `migration_model` and `databasechangelog` are created and rows are getting inserted (and everything is working fine).

So to me it looks like those errors are just keycloak checking if there already is an existing migration and databasechangelog, but an error is thrown, catched and then all migrations are being applied (table databasechangelog starts with `1.0.0.Final-KEYCLOAK-5461`).

Would be helpful if someone could confirm this theory, since those errors raise the fear that future keycloak migrations can not be applied because something at the initial startup went wrong.

**Comment by pedroigor** [comment]
If those logs are from the postgres server, they make sense. Keycloak is checking if the schema is there.

**Comment by jamesdh** [comment]
🤦‍♂️ @pedroigor you're absolutely right. Can't believe I missed that!

**Comment by bartlomiejduda** [comment]
Issue still occurs in keycloak **v24.0.5** and postgres **v15.2**.

Any solutions for that?

**Comment by atul-agg** [comment]
This issue still occurs in 26.3.1. Any solution for it?

**Comment by atrujillofalcon** [comment]
Issue still ocurrs in 26.3.2 with postgres v13.20

**Comment by atul-agg** [comment]
@pedroigor can you please help in resolving this?

**Comment by dioubernardo** [comment]
I'm seeing this on a quay.io/keycloak/keycloak:26.4.0 with postgresql 17. Empty installation on first up.
