### ISSUE TITLE
new operator: Keycloak 18.0.1-pod fails to start when nightly was deployed earlier

### ISSUE THREAD

**Issue by ibotty** [keycloak/keycloak#12630]
### Describe the bug

I deployed keycloak using the new operator using an optimized image built from `quay.io/keycloak/keycloak:nightly` (`sha256:4e333fcf6706445dc8b662758ae58c5a837972fc699f963256205000ba78495c8`).  Now I wanted to roll back to an optimized image built from `18.0.1`.

When updating the image reference in the `keycloak` crd, the pod fails starting with the following error.

```
2022-06-21 11:02:19,261 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: token_exchange
2022-06-21 11:02:19,275 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: keycloak-auth.<redacted>, Strict HTTPS: true, Path: <request>, St
rict BackChannel: false, Admin: <request>, Port: 443, Proxied: false
2022-06-21 11:02:20,337 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-06-21 11:02:20,350 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-06-21 11:02:20,378 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-06-21 11:02:20,673 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-06-21 11:02:20,910 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-06-21 11:02:21,149 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-755ff4bb47-5vqmr-47284|56] (3) [keycloak-755ff4bb47-5vqmr-47284, keycl
oak-755ff4bb47-6hfs4-64361, keycloak-5ff9968f68-p6sbx-7018]
2022-06-21 11:02:21,157 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-5ff9968f68-p6sbx-7018`, physical addresses are `[172.21.7.173:7800]`
2022-06-21 11:02:21,751 WARN  [org.infinispan.statetransfer.InboundTransferTask] (jgroups-12,keycloak-5ff9968f68-p6sbx-7018) ISPN000210: Failed to request state of cache authenticationSessions from node keycloak-7
55ff4bb47-5vqmr-47284, segments {4-11 18-22 29-54 60-69 112-118 204-226}: org.infinispan.commons.CacheException: ExceptionResponse(java.io.EOFException)
        at org.infinispan.statetransfer.InboundTransferTask.lambda$startTransfer$3(InboundTransferTask.java:167)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at org.infinispan.remoting.transport.AbstractRequest.complete(AbstractRequest.java:67)
        at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
        at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1495)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1397)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:145)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1582)
        at org.jgroups.JChannel.up(JChannel.java:780)
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
        at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
        at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
        at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
        at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
        at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
        at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
        at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
        at org.jgroups.protocols.Discovery.up(Discovery.java:300)
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
        at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
```

### Version

18.0.1

**Comment by stianst** [comment]
This will be caused by having multiple different versions of Keycloak running in the same cluster concurrently, which is not supported with the old store. The old store also doesn't support ability to downgrade after an upgrade, as there can be incompatible changes made to the database in the meantime. Going to close this one, but this is something we are working on supporting with the new store.

**Comment by ibotty** [comment]
I see.  I fixed the deployment by scaling down the old replicaset.  Thank you!

**Comment by biertz** [comment]
I'm experiencing the same error when updating a non-persistent, not replicated test-instance from version 18.0.0 to 18.0.1. Any ideas?

**Comment by ibotty** [comment]
Just delete the old pods.  Seems a HA-solution is not possible ATM.

**Comment by sebastienmoreno** [comment]
Experiencing the same issue.  
Is there solution where you clear the cache before upgrading preventing to have version incompability?

**Comment by biertz** [comment]
The error is specific to my setup then (that is: to my setup in connection with 18.0.1; 18.0.0 works fine). The error persists even with fresh containers and even starting directly from quay.io/keycloak/keycloak:18.0.1.
