### ISSUE TITLE
SAML client ignores Name ID format and Force name ID format parameters

### ISSUE THREAD

**Issue by Madmess** [keycloak/keycloak#14798]
### Describe the bug

For any type of NameID in the **Name ID format** and when **Force name ID format** is active we get username with unspecified type in the Keycloak response like this
<saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">username</saml:NameID>

### Version

19.0.3

### Expected behavior

Expected response for persistent Name ID format and Force name ID format is on
<saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">c727a4a6-2f63-4a3c-ae9a-4349b179268f</saml:NameID>

We use NameID mapper for persistent to LDAP_ID
LDAP_ID = c727a4a6-2f63-4a3c-ae9a-4349b179268f

This is example from 18.0.2 version

### Actual behavior

Actual response for persistent Name ID format and Force name ID format is on
<saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">username</saml:NameID>

### How to Reproduce?

Create SAML client
Select persistent in Name ID format
Activate Force name ID format
Check Keycloak response

### Anything else?

Keycloak 18.0.2 works fine with the same parameters

**Comment by Madmess** [comment]
Does anyone have the same problem?

**Comment by Madmess** [comment]
The issue does not reproduce on version 20.0.1

**Comment by rmartinc** [comment]
I have tested this with version 21.0.1 and it's working for me. I configured my client to request `<samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"/>` and the server is correctly forcing persistent in th e response `<saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">G-8460a2c8-7591-4b76-8331-641b0a78668e</saml:NameID>`. I see that you commented the same with 20.0.1.

I don't see any changes in this part so probably more related to the issues in the console with the boolean properties. But it doesn't matter, it should work now.

Closing the issue.

**Comment by dreznichuk** [comment]
Just in case someone still facing this issue

kc version: 20.0.1

saml client attributes contains duplicated key:
(from chrome developer tools)
```
{
    ...
    "attributes":
        {
            ...
            "saml_force_name_id_format": "false",
            "saml.force.name.id.format": "true",
            ....
        }
}
```

while UI is changing key with name `saml.force.name.id.format`, the right one is `saml_force_name_id_format`

changed manually with curl and it started to work

**Comment by edupr91** [comment]
REALLY NICE FINDING @dreznichuk. I exported the JSON client, modified the attribute with the right one, and re-created the client by importing the JSON. 

Thanks A LOT!

**Comment by Addvilz** [comment]
@rmartinc I believe this should be re-opened, see above

**Comment by rmartinc** [comment]
@Addvilz I think that was an issue in new console UI that was fixed the previous year https://github.com/keycloak/keycloak/issues/17815. So it's now fixed in current versions.

**Comment by jonkoops** [comment]
I am limiting conversation on this issue. If anyone can reproduce this in he latest version of Keycloak, then please submit a new issue.
