### ISSUE TITLE
NPE on welcome page if setting spi-theme-default and not providing theme

### ISSUE THREAD

**Issue by deibl** [keycloak/keycloak#15476]
### Area

admin/ui

### Describe the bug

When setting default theme (via --spi-theme-default) and not proving theme, fallback mechanism seems to cause a NPE on "/" admin/welcome page.
Motivation for not providing it: we only add some css to slightly modify the realm specific login page, about other pages we do not care as they are not public available.
Welcome pages used to work with 19.0.3 and ist now broken with 20.0.1

### Version

20.0.1

### Expected behavior

When setting --spi-theme-default and not proving theme, fallback should be used and welcome page should be showen

### Actual behavior

When setting --spi-theme-default and not proving theme, fallback cause NPE and thus 500 instead of displaying page.

### How to Reproduce?

/opt/keycloak/bin/kc.sh start --spi-theme-default=any
-> Open welcome page

### Anything else?

Stacktrace:
2022-11-13 10:35:19,288 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-0) Failed to find WELCOME theme any, using built-in themes
2022-11-13 10:35:19,288 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: javax.ws.rs.WebApplicationException: HTTP 500 Internal Server Error
	at org.keycloak.quarkus.runtime.services.resources.QuarkusWelcomeResource.createWelcomePage(QuarkusWelcomeResource.java:210)
	at org.keycloak.quarkus.runtime.services.resources.QuarkusWelcomeResource.getWelcomePage(QuarkusWelcomeResource.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at org.keycloak.quarkus.runtime.services.resources.QuarkusWelcomeResource.createWelcomePage(QuarkusWelcomeResource.java:174)
	... 46 more

**Comment by mposolda** [comment]
Setting to 22 as this is regression. Also it should be probably easy to fix.

Just a note that NPE exists on this line due the previous `getTheme()` call returned null: https://github.com/keycloak/keycloak/blob/20.0.1/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/QuarkusWelcomeResource.java#L174

One side note: It is possible that it is fixed in latest Keycloak 21.0.1. But not sure, we can doublecheck...

**Comment by deibl** [comment]
> 

Actually i did check with KC 21.0.1 last week and issue was still present.
Happy to here it is getting fixed <3

**Comment by pedro-hos** [comment]
Hey @mposolda can you review the PR? =D 
Thanks, man

**Comment by kaes1** [comment]
This issue is **not** fixed in Keycloak 22.0.5.

The [change above](https://github.com/keycloak/keycloak/commit/aa9744246c634a408ac3fa30fb8d0f2d82aee060) only prevents NPE by returning a 400 error response, but the underlying issue is still present. 

When using "-spi-theme-default=any" and not providing an "any" WELCOME theme, Keycloak returns an error, instead of using a built-in theme.

```
2023-11-23 17:50:50,908 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-1) Failed to find WELCOME theme any, using built-in themes
2023-11-23 17:50:50,908 ERROR [org.keycloak.quarkus.runtime.services.resources.QuarkusWelcomeResource] (executor-thread-1) Theme is null please check the "--spi-theme-default" parameter
```

This results in a simple error in the browser:  
![image](https://github.com/keycloak/keycloak/assets/22614333/0b7a11a6-7c39-45c3-ba9e-22e76df46a41)

The log message _says_  it's "using built-in themes", but it actually isn't.

The expected behavior is that if "any" theme for WELCOME page is not found, a message is logged, and a built-in theme (eg. "keycloak" or "keycloak.v2" or whatever is up-to-date) is used instead.
