### ISSUE TITLE
Unable to use environment variables within realm configuration files

### ISSUE THREAD

**Issue by nuwang** [keycloak/keycloak#20199]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

The docs state that it is possible to perform environment variable substitutions when importing realms: https://www.keycloak.org/server/importExport

However, as reported by others elsewhere as well (https://stackoverflow.com/questions/64835574/is-system-environment-variable-allowed-in-keycloak-realm-json), this does not work. The issue is particularly problematic because there does not appear to be any mechanism currently for safely importing credentials during import/export, for Kubernetes in particular.

### Version

21.1.1

### Expected behavior

Given a substitution like:
```
    credentials:
      - type: password
        value: "${MY_ADMIN_PASSWORD}"
```
The variable ${MY_ADMIN_PASSWORD} should be replaced with the corresponding envvar value.

### Actual behavior

The substitution is not processed, and the value is stored as a literal, even though the environment variables are available within the container.

### How to Reproduce?

In the following sample operator import/export, the values are not substituted. The same can be reproduced through a manual import in the UI.

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: test-import
  labels:
    app: my-keycloak
spec:
  keycloakCRName: my-keycloak
  realm:
    id: test
    realm: test
    users:
      - id: 3a26bfa5-65f3-4e4c-b78d-41eed0b9763c
        emailVerified: true
        username: admin
        enabled: true
        totp: false
        emailVerified: true
        firstName: a
        lastName: b
        email: a@b.com
        credentials:
          - type: password
            value: "${MY_ADMIN_PASSWORD}"
    clients:
      - id: f30eb3df-ba4a-42fa-9165-49ab8bbadb38
        clientId: my-client
        clientAuthenticatorType: client-secret
        secret: "${MY_CLIENT_SECRET}"
```

### Anything else?

Vault substitutions also do not work.
https://github.com/keycloak/keycloak-realm-operator/issues/8

And there does not appear to be any other mechanism for injecting secrets safely.

**Comment by tanathap** [comment]
I also ran into this issue too and looking for a solution. In my case in ran with docker and had check that env has already set to container but still can not inject env to realm config file.

**Comment by hmlnarik** [comment]
@vmuzikar This is related to cloud, could you please triage?

**Comment by shawkins** [comment]
@nuwang to make sure I understand the environement variables have been added to the Keycloak CR for availability in the Keycloak pods, and then you are referencing those in the KeycloakRealmImport?

I see that any env configuration from the keycloak cr is not added to the job itself.

> The issue is particularly problematic because there does not appear to be any mechanism currently for safely importing credentials during import/export, for Kubernetes in particular.

Would a more kube like mechanism be desirable?  That is would it make sense to specify something like envFrom referencing a secret directly on the KeycloakRealmImport.

> However, as reported by others elsewhere as well (https://stackoverflow.com/questions/64835574/is-system-environment-variable-allowed-in-keycloak-realm-json), this does not work.

That also seems to imply the feature doesn't seem to work in general.  The doc does specifically talk about environment variables in reference to "When importing a realm at startup", but the import job is a regular import.

**Comment by nuwang** [comment]
@shawkins Thanks for looking into this. That's correct. I've injected the env vars into the keycloak CR as follows:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: mykeycloak
  namespace: keycloak
spec:
  instances: 1
  # omitted for brevity
  unsupported:
    podTemplate:
      spec:
        containers:
          - volumeMounts:
              - name: vault
                mountPath: /opt/keycloak/secrets
            env:
              - name: MY_ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: keycloak-admin-password
                    key: password
```

I've just double checked and can confirm that the same variables are passed into the batch job - they appear to be getting copied over from the keycloak container spec.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-import
  namespace: keycloak
spec:
    spec:
      containers:
        - args:
            - '-c'
            - >-
              /opt/keycloak/bin/kc.sh import
              --file='/mnt/realm-import/my-realm.json' --override=false
          command:
            - /bin/bash
          env:
	    # Some sections omitted for brevity
            - name: MY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: keycloak-admin-password
```

> That also seems to imply the feature doesn't seem to work in general. The doc does specifically talk about environment variables in reference to "When importing a realm at startup", but the import job is a regular import.

> Confirmed this is the case:

If it's mainly a matter of turning on substitution processing in the import job using `ExportImportConfig.setReplacePlaceholders(true); ` that sure sounds like a very reasonable way to leverage existing keycloak mechanisms + kube env var injection to securely handle secrets. This would be a significant improvement over the current situation where the only available mechanism is to hard code the secrets into the unencrypted RealmImport CR. In the longer term, I suppose custom CRs could provide an even more kube-native way to manage such secrets.

**Comment by shawkins** [comment]
> I think what we need to do for this is pass -Dkeycloak.migration.replace-placeholders=true to the java command.

@nuwang you should actually already be able to override JAVA_OPTS_APPEND as an env variable on the keycloak cr to accomplish this - could you try adding 

```
- name: JAVA_OPTS_APPEND
  value: "-Dkeycloak.migration.replace-placeholders=true"
```

And see if it works as expected.

**Comment by nuwang** [comment]
@shawkins It works nicely! Thanks for that.

I did run into the following issue while testing this:
```
2023-06-22 11:42:24,957 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2023-06-22 11:42:24,957 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.StackOverflowError
	at org.keycloak.common.util.StringPropertyReplacer.replaceProperties(StringPropertyReplacer.java:134)
	at org.keycloak.common.util.StringPropertyReplacer.replaceProperties(StringPropertyReplacer.java:241)
	at org.keycloak.common.util.StringPropertyReplacer.replaceProperties(StringPropertyReplacer.java:241)
	at org.keycloak.common.util.StringPropertyReplacer.replaceProperties(StringPropertyReplacer.java:241)
	at org.keycloak.common.util.StringPropertyReplacer.replaceProperties(StringPropertyReplacer.java:241)
	at org.keycloak.common.util.StringPropertyReplacer.replaceProperties(StringPropertyReplacer.java:241)
	at org.keycloak.common.util.StringPropertyReplacer.replaceProperties(StringPropertyReplacer.java:241)
	at org.keycloak.common.util.StringPropertyReplacer.replaceProperties(StringPropertyReplacer.java:241)
```

The reason for that was because I had originally set the password in the secret to `${MY_ADMIN_PASSWORD}`, which was also the value of the template string in the realm import:
```
        credentials:
          - type: password
            value: "${MY_ADMIN_PASSWORD}"
```
Looks like that causes infinite recursion. Once I fixed that, it all worked nicely, but just thought of reporting it in case it's unintended behaviour.

Thanks again.

**Comment by tedherring-smarsh** [comment]
@shawkins thanks for linking my issue here, I'm happy to see work has already been done here.  However it does not seem to work for me even with the JAVA_OPTS_APPEND set I'm still getting a literal in the realm.  

I can see it logs the append
`Appending additional Java properties to JAVA_OPTS: -Dkeycloak.migration.replace-placeholders=true`

But the literal persists.  Any other suggestions?  I've confirmed the env var for the secret exists, but can't seem to get it to pull in the referenced value

**Comment by tedherring-smarsh** [comment]
@shawkins thanks for the link, the addtion of the env var to append the java worked, cheers!
