### ISSUE TITLE
Search groups is not returning all the subtree structure

### ISSUE THREAD

**Issue by nirhil10** [keycloak/keycloak#20445]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I have the following groups structure:
<img width="197" alt="image" src="https://github.com/keycloak/keycloak/assets/11706338/e8363237-9528-4a00-ab8f-8aec5b515dc0">

when I search for group 'Test' I got this result:
<img width="220" alt="image" src="https://github.com/keycloak/keycloak/assets/11706338/716b1944-5318-4152-9412-97e15343459d">

same result in the admin rest api:
<img width="369" alt="image" src="https://github.com/keycloak/keycloak/assets/11706338/82228802-34aa-4218-b242-b0c0109ca16d">

i would expect to get all the groups structure of group Test and group Test1

### Version

21.1.1

### Expected behavior

To get all the searched group structure including subgroups.
In my case:
<img width="197" alt="image" src="https://github.com/keycloak/keycloak/assets/11706338/e22e678e-b91d-4593-85c0-228327bb607e">

### Actual behavior

Get only part of the subgroups.

### How to Reproduce?

1. create group with subgroups.
2. search for the parent group

**Comment by mposolda** [comment]
I think this is expected behaviour and it works like this due the performance.

@thomasdarimont Maybe you remember some related issue, which was done due the performance (AFAIR you were contributing it some time ago, but I may be wrong...)

**Comment by nirhil10** [comment]
> I think this is expected behaviour and it works like this due the performance.
> 
> @thomasdarimont Maybe you remember some related issue, which was done due the performance (AFAIR you were contributing it some time ago, but I may be wrong...)

@mposolda, can you please describe what is the logic of returning this structure? For me it doesnt make any sense to return the subgroup of one finding but not the subgroup of the other finding..

**Comment by nirhil10** [comment]
> > I think this is expected behaviour and it works like this due the performance.
> > @thomasdarimont Maybe you remember some related issue, which was done due the performance (AFAIR you were contributing it some time ago, but I may be wrong...)
> 
> @mposolda, can you please describe what is the logic of returning this structure? For me it doesnt make any sense to return the subgroup of one finding but not the subgroup of the other finding..

@mposolda, @thomasdarimont , I really appreciate your reply here. Currently it seems like a bug for me and my team.

**Comment by pedroigor** [comment]
@mposolda From a user perspective, the behavior is not correct because you do want to keep the same format as when you are listing the groups. Does not look reasonable to me to change the format just because you are querying groups.

@thomasdarimont It also looks related to https://github.com/keycloak/keycloak/pull/16540.

**Comment by hmlnarik** [comment]
> @mposolda @nirhil10 I took a look and I think that the group search matching is currently broken.
> 
> I created a PR with a fix (including a test with the example from this issue): #20513

The behaviour is flawed, IMO only parent groups of the matching group should be returned, and no child groups.

@thomasdarimont What is your suggestion re the fix?

**Comment by nirhil10** [comment]
> of the matching group should be returned, and no child groups.

@hmlnarik , The behavior is truly flawed as it is now. But i think to better return the matching groups with all its sub groups, and leave the client the option to filter the subgroups.

**Comment by nirhil10** [comment]
dasd

> @mposolda @nirhil10 I took a look and I think that the group search matching is currently broken.
> 
> I created a PR with a fix (including a test with the example from this issue): #20513

Thank u @thomasdarimont. So we can expect for a fix in the coming release, right?

**Comment by thomasdarimont** [comment]
@nirhil10 I think we need to first get an alignment on the desired behaviour before this can get into a release :)

**Comment by pedroigor** [comment]
@nirhil10 @thomasdarimont We should also take into account the UI/UX when using the admin console.

One of the main issues about the endpoint we are discussing is that it resolves the group hierarchy beforehand even though you might not be interested in the group hierarchy. Ideally, we should only resolve hierarchy when actually wanted and avoid the overhead of doing so all the time.

However, this should involve mode changes not only to this endpoint but also to the clients using the API such as the admin console.

To keep things simple, I would keep some minimum level of idempotency by merging  https://github.com/keycloak/keycloak/pull/20513. The result should not be different at all if you are querying groups.

Then, I would review the meaning of `briefRepresentation` and make sure that when it is used, we only return the matching groups, with minimal data/representation, and no hierarchy.

By doing that we are fixing this issue as well as https://github.com/keycloak/keycloak/issues/16535.

**Comment by hmlnarik** [comment]
+1 to the @thomasdarimont 's proposal.

> To keep things simple, I would keep some minimum level of idempotency by merging https://github.com/keycloak/keycloak/pull/20513. The result should not be different at all if you are querying groups.

I agree with this conservative approach.

> Then, I would review the meaning of `briefRepresentation` and make sure that when it is used, we only return the matching groups, with minimal data/representation, and no hierarchy.

The `briefRepresentation` flag was meant to return the full vs partial set of properties of resulting objects, like excluding attributes. It works this way for other objects too, e.g. users, roles etc. For that reason, I'd expect `briefRepresentation` to affect the set of returned group properties rather that the ability to return the group hierarchy. For not including the hierarchy, I'd thus prefer a separate flag, say `includeParents` with default to `true`.

**Comment by pedroigor** [comment]
@hmlnarik About the `briefRepresentation`.

That is true but on the other hand, you might consider the hierarchy as being among the full set of properties. My main point is that introducing another parameter might introduce more complexity. I think it is reasonable to set `briefRepresentation` to `false` and expect that hierarchies are not returned.

So we have something like this:

* `true`, the endpoint returns the matching groups within their hierarchies and their full set of attributes
* `false`, the endpoint returns the matching groups with the minimal set of attributes

**Comment by hmlnarik** [comment]
> FYI the admin-ui REST-Interface for group search supports a "global" parameter to limit search only to top level groups: https://github.com/keycloak/keycloak/blob/main/rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java#L56
> 
> We should consider supporting this for the groups admin resource resource too.

+1, and it could be done more generally by search under a specified parent (`parentId` parameter would be either set, or not meaning top-level). This would be more resource-friendly than searching the whole groups hierarchy at once. In the case of UI, it would allow lazy loading of direct children of a node which could be leveraged for more efficient walk of the the group tree.

**Comment by hmlnarik** [comment]
> @hmlnarik About the `briefRepresentation`.
> 
> That is true but on the other hand, you might consider the hierarchy as being among the full set of properties. My main point is that introducing another parameter might introduce more complexity. I think it is reasonable to set `briefRepresentation` to `false` and expect that hierarchies are not returned.
> 
> So we have something like this:
> 
> * `true`, the endpoint returns the matching groups within their hierarchies and their full set of attributes
> * `false`, the endpoint returns the matching groups with the minimal set of attributes

I see your point. It seems to me that the uses are the following:

1. `briefRepresentation` = `false` and `populateHierarchy` = `false` (to display details of the group),  or
2. `briefRepresentation` = `true` and `populateHierarchy` = `false` (to search groups and get their list), or
3. `briefRepresentation` = `true` and `populateHierarchy` = `true` (to search groups for displaying them in a tree).

Having them attached to one another as you suggest would work for 1. but not allow distinguishing 2. and 3.

Thus I would keep the options separate, as there is a need for it (see #16535).

**Comment by rweintraub-cycleon** [comment]
whats the status of this ticket? we've recently upgraded to keycloak 22 (we skipped 21) and our users are complaining about the confusing search results for nested groups

**Comment by MartaGolabek** [comment]
Same here, our users are also complaining about confusing search results for groups in admin console. Also IMHO search should be case insensitive as long as "exact search" is not selected.

**Comment by Redhat-Alice** [comment]
There is currently an epic open to address scalability with groups that includes some large reworks for how search functions among other things: https://github.com/keycloak/keycloak/issues/22261

On [this specific PR](https://github.com/keycloak/keycloak/pull/22700) I have added a commit that should address these issues with JPA. I believe that the issue with the map storage providers was solved while working on the other enhancements for this PR

**Comment by MartaGolabek** [comment]
> +1 to the @thomasdarimont 's proposal.
> 
> @rweintraub-cycleon Same here, our users are also complaining about confusing search results for groups in admin console. Also IMHO default search should be case-insensitive as long as "exact search" is not selected.
> 
> My groups: ![image](https://private-user-images.githubusercontent.com/15276644/266526700-6c949097-0b48-49f3-bff8-6e96b744aa05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzkxMTUsIm5iZiI6MTcwNjI3ODgxNSwicGF0aCI6Ii8xNTI3NjY0NC8yNjY1MjY3MDAtNmM5NDkwOTctMGI0OC00OWYzLWJmZjgtNmU5NmI3NDRhYTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE0MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MDU4YmUyMWQ5MTM4NWY1ZmQ3MmQ4YTI5OTRlNGFhZGEyZGQyOTQwYWIwZjMxZDc2YzE2NGRkYTc0Yzc5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ZH9DdVpNhEXEdp9j-onZI0fMwfBgWp7RhNIsNgPLy8)
> 
> Searching for 'casesensitive', group 'CASESENSITIVE' isn't found, because it is written in uppercase :( ![image](https://private-user-images.githubusercontent.com/15276644/266526967-1604d4f6-7945-46d7-a98b-4641466b7872.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzkxMTUsIm5iZiI6MTcwNjI3ODgxNSwicGF0aCI6Ii8xNTI3NjY0NC8yNjY1MjY5NjctMTYwNGQ0ZjYtNzk0NS00NmQ3LWE5OGItNDY0MTQ2NmI3ODcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE0MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NDE4ZmVmZDVlYmI1NzljOTA0NjdiZTdlYzY1MWYzNzcxNTM3YWIxNjBkZGIzODQ5YjlmZjQzZWM3YTk1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.veB47Tie_UF8AYETyXm1Y-HM0WlwGfYe4Vlw1Fa77q4)

**Funktioniert in Keycloak 23.0.4:**
![image](https://github.com/keycloak/keycloak/assets/15276644/e8a7770f-f9bc-4922-9934-0939466b26f6)

![image](https://github.com/keycloak/keycloak/assets/15276644/8257aa23-a786-44ce-98a0-d9d690b061f2)

**Comment by MartaGolabek** [comment]
But the search functionality in sub groups still doesn't work. Typed search term is not reflected in the search hits. All subgroups are still returned.

![image](https://github.com/keycloak/keycloak/assets/15276644/7a8a2fa9-c43d-4b83-9048-1dc2aec6f7dc)

**Comment by alice-wondered** [comment]
This method is available after the groups rework
https://github.com/keycloak/keycloak/blob/b7d2010af7f290d559c36c220d8cf89a85d0b1d2/server-spi/src/main/java/org/keycloak/models/GroupModel.java#L125-L145

I think it needs to be re-worked a bit to not use streams and search/paginate at the db layer instead of in streams, but that should be similar to how any other group search works at this point. 

Then the API can be expanded to allow for searching on child groups here: 
https://github.com/keycloak/keycloak/blob/b7d2010af7f290d559c36c220d8cf89a85d0b1d2/services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java#L154-L168

Which would allow for the UI to fix this issue easily
