### ISSUE TITLE
Refreshed Access Tokens don't have the original's audience claim

### ISSUE THREAD

**Issue by alt-enio** [keycloak/keycloak#20517]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

An Access Token is requested to Keycloak using scope "x-api" to get aud claim with value "x-api" which succeeds. Later when that token expires we use the Refresh Token to get another Access Token, but this time no aud claim is sent.

The client is set up using an optional Client Scope "x-api" that contains an Audience Mapper that outputs a custom audience "x-api".

The Client Scope was assigned as Optional to force the client to include it explicitly in the "scope" parameter when authenticating. If the Client Scope is assigned as Default, the behavior is the expected. (The aud claim is always sent.)

I also tried to pass a "scope" parameter when requesting the new Access Token but it seems it was ignored.

### Version

21.1.1

### Expected behavior

The Access Token requested using the Refresh Token should contain the same "aud" claim as the original one.

### Actual behavior

The Access Token requested using the Refresh Token lacks the "aud" claim which makes any requests to the intended API fail the audience validation.

### How to Reproduce?

* Set up a Client with a Client Scope - "x-api" - assigned as Optional. This Client Scope must have a Audience Mapper to set "x-api" audience.
* Authenticate a user (standard flow) with the Client. (Must include scope x-api in the request.)
* Verify that the received Access Token contains the "aud" claim.
* Request a new Access Token using the Refresh Token
* Verify that the new Access Token does not contain the "aud" claim.

**Comment by jsorah** [comment]
Hi, thanks for the details here - can you confirm the exact settings on the scope or provide a screenshot of the configuration? I was able to replicate it on 21.1.1, but only when "Include in token scope" is deselected on the Client Scope, and wanted to confirm if that was the case for you as well.

I also think this affects any mappers added to the scope, as I added a hardcoded claim and it was not present in the access token after using the refresh token.

---- 

Testing notes

Scope Setup
![image](https://github.com/keycloak/keycloak/assets/4944041/9709f205-768e-4210-b900-49cad6cceceb)

Scope audience mapper
![image](https://github.com/keycloak/keycloak/assets/4944041/20e7bfb6-e2d0-4f52-868b-cbf2b4110bd7)

Access Token:
![image](https://github.com/keycloak/keycloak/assets/4944041/9ec927da-9175-4650-8ee2-986a918792e7)


Using refresh token (using httpie, jq, jwt-cli) :

```
http -f :8080/realms/master/protocol/openid-connect/token client_id=js-test grant_type=refresh_token refresh_token="${REFRESH_TOKEN}" | jq -r .access_token | jwt decode - -j | jq .payload.aud
[
  "master-realm",
  "account"
]
```

**Comment by jsorah** [comment]
This also impacts ID tokens.

**Comment by pedroigor** [comment]
@alt-enio During a refresh token request, Keycloak only resolves the scopes previously included in the token response and in the access token. That is why you don't see the audience set by the mapper.

The workaround is to enable that switch, as already suggested by @jsorah. I understand it is not the best (you don't want that scope in the token or the token response) but it is what it is.

However, I think we should review how scopes are handled when issuing refresh tokens because the fact the scope is not available from the token response does not mean it should be lost when refreshing tokens. Accordingly to the [specs](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#section-4.3.1), if the `scope` parameter is omitted in the refresh token request, it must be treated as equal to the scope originally granted by the resource owner.

AFAIK, Keycloak does not support the `scope` parameter when refreshing tokens, any scope previously granted should be considered when refreshing tokens. This is basically the issue we are facing here.

Resolving the audience based on client scopes is problematic because the audience is not really something the resource owner is granting and it does not represent access to a protected resource but the target audience where the token can be presented. Resource servers use the audience to perform a coarse-grained check to make sure they are the intended recipients of a bearer token and it represents the identity of a set of one or more resources where the token can be used.

On the other hand, scopes are meant to enable more fine-grained access once the bearer token is accepted by a resource server so that it can control how clients can access its protected resources.

Keycloak is mixing both concepts and resolving audiences as if they were scopes. IMO, not aligned with the specs.

I'm pretty sure we won't fix that now due to the amount of work to make it right.

However, it should be possible to provide an alternative solution that stores (within the refresh token or in the client session) all the scopes (including those not included in the original token response) to make it possible to run the mappers that are missing (like your audience mapper).

Another option is to re-evaluate the client scopes during a refresh instead of relying on the scopes included into the original token response. This one might introduce an additional overhead, not sure how much because data should be cached.

There are other options but they are basically fixing the core issue I mentioned before and should involve more changes.

@mposolda Wdyt?

**Comment by alt-enio** [comment]
@pedroigor, I can confirm that adding the `scope` parameter to the refresh token request to get the new token did not affect the outcome.

**Comment by stianst** [comment]
Regardless if client scope and audience are better or worse than resource it should still work. I honestly think it works quite well to have a client scope that adds aud, and make it an optional thing as that allows me to easily get an access token for a dynamic set of audiences. If https://github.com/keycloak/keycloak/issues/24323 is fixed as well as part of this then you can easily get a refresh token with all scopes, then request a smaller scoped access token from the refresh token with the bigger scope. Whether or not I use scopes or resource for this purpose should be up to the user (especially seeing that resource is not in the core specs, but an extension). In the end both should work.

**Comment by vickeybrown** [comment]
After some testing, it looks like #12009 didn't fix this issue.

**Comment by heri2468** [comment]
Is the following issue not yet closed ? 
In recent versions also, I am facing same situation that whenever optional client scopes are added as part of refresh_token grant flow, it doesnt get mapped to access token.
