### ISSUE TITLE
custom user storage provider update in admin-ui disables it, and stores value “t” as enabled

### ISSUE THREAD

**Issue by rvanderboom** [keycloak/keycloak#21234]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

we have an custom userstorage provider.
after upgrade to the new react admin we notice when doing an update via the admin for our custom provider, the admin user semding “t”. as enabled which put everything to readonly.
when disabling and enabling the provider again the value is restored to “true”.
but this repeats every time a  updat is done (different from the enable/disable switch).
we also see the value Posted in the json to the keycloak admin endpoints as “enabled”: “t” in stead of true.

it looks like something todat with the commom:enabled types im admin ui, but not sure.

we use the latest 21.1.0

### Version

21.1.0

### Expected behavior

after updating a custom field in our custom user provider (implemts userstorageprovider), we don’t expect the default enable flag to be stored as value “t”, which disables all update.writes of all users.

### Actual behavior

see description of the issue, its only caused by update in the new admin-ui for a custom user storage provider.

### How to Reproduce?

create a simple custom userprovider with 1 custom field (or update the cache setting).

### Anything else?

no, easy to test with custom user storage provider

**Comment by rvanderboom** [comment]
mmm maybe relates to: issue 820028 (https://github.com/keycloak/keycloak/issues/19638).
doesn’t mention admin-ui but the workaround  disable/enble seems to be simular

**Comment by robvanderboom** [comment]
the "t" seems fix with issue 19638 BUT, in the provider admin screen the toggle is always shown as disabled even the provider is enabled, so this is not correct

**Comment by rvanderboom** [comment]
Hey,

no this is already up to date, we had the latest 2 weeks ago, and changed the Header.tsx with the changes doen very recent.
Now overall it is improved but still this button always says disabled when refreshing the page:

As you can see the overview is allways correct and so is the rest of the functionality, but the detailed page shows disabled always.

We do have ldap that is enabled and shows it correctly


Rob.



The change in 20097 is already in our build.

Rob

________________________________
Van: Stan Silvert ***@***.***>
Verzonden: woensdag 28 juni 2023 20:32
Aan: keycloak/keycloak ***@***.***>
CC: Rob van der Boom ***@***.***>; Author ***@***.***>
Onderwerp: Re: [keycloak/keycloak] custom user storage provider update in admin-ui disables it, and stores value “t” as enabled (Issue #21234)


@robvanderboom<https://github.com/robvanderboom> Can you try this in the latest nightly build?

#20097<https://github.com/keycloak/keycloak/issues/20097>

**Comment by edewit** [comment]
So you are saying that you would want the invalid data that you have now, because of this bug, to be automatically be fixed with any update?

**Comment by rvanderboom** [comment]
the disabled/enabled flag on the provider page always shows disabled, it would be nice if this is solved in an upcoming bugfix.


Rob

Rob
Software Developer
________________________________
Van: Erik Jan de Wit ***@***.***>
Verzonden: vrijdag 30 juni 2023 15:22
Aan: keycloak/keycloak ***@***.***>
CC: Rob van der Boom ***@***.***>; Author ***@***.***>
Onderwerp: Re: [keycloak/keycloak] custom user storage provider update in admin-ui disables it, and stores value “t” as enabled (Issue #21234)


So you are saying that you would want the invalid data that you have now, because of this bug, to be automatically be fixed with any update?

**Comment by edewit** [comment]
@robvanderboom I'm not sure what you mean, but I think that https://github.com/keycloak/keycloak/pull/20964 fixes this

**Comment by rvanderboom** [comment]
Hey,

no that is exactly what i am trying to explain, i got the latest version which includes 20964, but it doesn't fix the enabled/disabled flag on the detailed page.
It does update correctly when for example putting it to enabled, but if you refresh the page, the toggle always shows "disabled"..
on the overview page it is correct and shows enabled when its enabled..

Rob.

Rob van der Boom
Software Developer
Prins Bernhardplein 173, 1097 BL Amsterdam
​Postbus 216, 1000 AE Amsterdam
***@***.***
www.fdmediagroep.nl
This message may contain confidential (business) information and / or information which falls under the protection of journalistic sources and should be treated as such. If you are not the addressee of this message, please destroy this message without taking note of the content and do not use, copy and/or distribute this message and its content to others.
________________________________
Van: Erik Jan de Wit ***@***.***>
Verzonden: maandag 3 juli 2023 13:14
Aan: keycloak/keycloak ***@***.***>
CC: Rob van der Boom ***@***.***>; Author ***@***.***>
Onderwerp: Re: [keycloak/keycloak] custom user storage provider update in admin-ui disables it, and stores value “t” as enabled (Issue #21234)


@robvanderboom<https://github.com/robvanderboom> I'm not sure what you mean, but I think that #20964<https://github.com/keycloak/keycloak/pull/20964> fixes this

**Comment by edewit** [comment]
I think it's still wrong in the database could you try and toggle it on and off and saving to make sure you have the right state?

**Comment by rvanderboom** [comment]
hey,

No sinds the latest updates, its ok in the database, and that is also seen due to the issue that users where first disabled is fixed.
Also the overview page of the custom storage providers (we have 2) is correct.. It shows enabled when enabled and disabled when one is set to disabled.
But on the detailed custom storage provider page , the toggle always shows disabled.

Because of this, fix 20964 at leased solved the functionality and is not 'breakng' for us.. But it should be nice if the enabled/disabled is also shown correctly on the detailed page.

Rob.

Software Developer

________________________________
Van: Erik Jan de Wit ***@***.***>
Verzonden: donderdag 6 juli 2023 08:18
Aan: keycloak/keycloak ***@***.***>
CC: Rob van der Boom ***@***.***>; Author ***@***.***>
Onderwerp: Re: [keycloak/keycloak] custom user storage provider update in admin-ui disables it, and stores value “t” as enabled (Issue #21234)


I think it's still wrong in the database could you try and toggle it on and off and saving to make sure you have the right state?
