### ISSUE TITLE
auth/admin/realms/{realm-name}/groups?briefRepresentation=false returns empty subgroups. 

### ISSUE THREAD

**Issue by KapilBillore** [keycloak/keycloak#27694]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Hi Team,

We have been migrating to KC 23.5 and observed that the /groups functionality doesn't return subgroups anymore and the field is empty. 
Can you suggest an alternative way/fix to handle the same? 

### Version

23.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The groups should be returned with subgroups populated.

### Actual behavior

Subgroup field is empty

### How to Reproduce?

https://{keycloak-host}:port/auth/admin/realms/{realm-name}/groups?briefRepresentation=false

**Comment by RichieB2B** [comment]
We are experiencing the same issue. I've read that with #22700 there now is a new `/admin/realms/{realm}/groups/{group-id}/children` paginated endpoint but nowhere is mentioned that `/admin/realms/{realm}/groups` will now always return empty `subGroups` (regardsless of what `briefRepresentation` is set to) .

This is a breaking change in the API that I wish was communicated more clearly.

**Comment by RichieB2B** [comment]
I have just tested this issue with Keycloak 24.0.1
As reported about `subGroups` is always empty. If this is not a bug (I think it should be) at least this should be clearly documented in the API documentation and upgrade guides.

Output for `/admin/realms/{realm}/groups`
```
[
  {
    "id": "98d4be1e-16db-45d0-9888-c6f32c00d968",
    "name": "top-group",
    "path": "/top-group",
    "subGroupCount": 2,
    "subGroups": [],
    "access": {
      "view": true,
      "viewMembers": true,
      "manageMembership": true
    }
  }
]
```
Output for `/admin/realms/{realm}/groups/98d4be1e-16db-45d0-9888-c6f32c00d968`
```
{
  "id": "98d4be1e-16db-45d0-9888-c6f32c00d968",
  "name": "top-group",
  "path": "/top-group",
  "subGroupCount": 2,
  "subGroups": [],
  "attributes": {},
  "realmRoles": [],
  "clientRoles": {},
  "access": {
    "view": true,
    "viewMembers": true,
    "manageMembers": true,
    "manage": true,
    "manageMembership": true
  }
}
```
Output for `/admin/realms/{realm}/groups/98d4be1e-16db-45d0-9888-c6f32c00d968/children`
```
[
  {
    "id": "65da20e5-e8d8-4fe8-b105-b437a85a9880",
    "name": "child1",
    "path": "/top-group/child1",
    "parentId": "98d4be1e-16db-45d0-9888-c6f32c00d968",
    "subGroupCount": 1,
    "subGroups": [],
    "attributes": {},
    "realmRoles": [],
    "clientRoles": {},
    "access": {
      "view": true,
      "viewMembers": true,
      "manageMembers": true,
      "manage": true,
      "manageMembership": true
    }
  },
  {
    "id": "901e1e5e-2541-4909-a87c-8f61f82703a6",
    "name": "child2",
    "path": "/top-group/child2",
    "parentId": "98d4be1e-16db-45d0-9888-c6f32c00d968",
    "subGroupCount": 1,
    "subGroups": [],
    "attributes": {},
    "realmRoles": [],
    "clientRoles": {},
    "access": {
      "view": true,
      "viewMembers": true,
      "manageMembers": true,
      "manage": true,
      "manageMembership": true
    }
  }
]
```

**Comment by RichieB2B** [comment]
@KapilBillore can you rename the title of this issue to:

auth/admin/realms/{realm-name}/groups always returns empty subGroups

**Comment by Skyppid** [comment]
We also experience this issue since the upgrade. I'm using a .NET library and logged the JSON response I get from both the groups endpoint:

`{"id":"7b05dd5f-1567-4c35-bdc8-b4a33eeb4d05","name":"Parent","path":"/Parent","subGroupCount":1,"subGroups":[],"attributes":{},"realmRoles":[],"clientRoles":{"***":["***"]},"access":{"view":true,"viewMembers":true,"manageMembers":true,"manage":true,"manageMembership":true}}`

(I obfuscated some parts though with ***)
As you see it says `subGroupCount: 1` but provides no groups. The group is not deeply nested, it's just one layer deep.

If I use the new endpoint for children I just get `[]` and that's it.

**Comment by RichieB2B** [comment]
@Skyppid Are you sure you called the `/children` endpoint correctly? It should return a list of `GroupRepresentation`:
```
GET /admin/realms/{realm}/groups/7b05dd5f-1567-4c35-bdc8-b4a33eeb4d05/children
```

**Comment by RichieB2B** [comment]
> I'm not sure if we are going to revisit this behavior. If I understand correctly, the issues reported here are:
> 
> * sub-group count returning a wrong value when no subgroups are returned
> * review how we are processing sub-groups when searching for top-level groups

My main issue is that a simple call to `/admin/realms/{realm}/groups` without any parameters is not populating `subGroups`. The [description](https://www.keycloak.org/docs-api/24.0.1/rest-api/#_groups) of this endpoint is:
```
Get group hierarchy. Only name and ids are returned.
```
Since 23.x it is not returning a hierarchy by default anymore. If that is by choice the description of the endpoint should reflect this. Maybe something like:
```
Search for groups. Without any parameters only the topmost groups are returned. The hierarchy in subGroups is not reliable, use /children instead.  
```
and set `populateHierarchy` to `false` by default.

**Comment by RichieB2B** [comment]
@pedroigor Can you confirm that requesting `/admin/realms/{realm}/groups` without any parameters not returning the group hierarchy is intended behaviour? If so, I'll make a PR to clearly mention this in the API docs.

**Comment by RichieB2B** [comment]
I still think this is a bug that should be fixed. Breaking an API like this without documenting it cannot be intentional IMHO.

**Comment by RichieB2B** [comment]
I think it speaks volumes that after introducing a breaking change without any warning or documentation, the developers can't decide if this was intended behaviour or a bug.

**Comment by Skyppid** [comment]
> Sorry I have to chime in. The keycloak admin API is probably one of the worst API's I have ever seen. Almost every field is optional and basically nothing is documented. In more cases than not it behaves differently than expected. Everything is trial and error, and it feels like you can not expect ANY consistency in responses between endpoints at all. This makes working with keycloak in strictly typed languages a true nightmare. I'm not writing this to just rant, but to press on that this is a serious issue.

Sadly true. They really need to improve there by a lot. One of the main reasons why we currently look into alternatives. I think some of the most critical issues on production we had were related to Keycloaks API...

**Comment by Aless55** [comment]
@RichieB2B 
I just wanted to use the **/admin/realms/{realm}/users/{user-id}/groups** endpoint. The subGroups are also always empty. 
Do you think this could be a similar problem? I tried adding **?search=** but it does not seem to fix the problem.
In contrary admin/realms/{realm}/groups?briefRepresentation=false works if the empty search term is appended.

We are on Keycloak 25.1.

**Comment by RichieB2B** [comment]
@Aless55 You are describing a similar problem with a different endpoint. Please open a new issue and reference this issue id if you think they are related.

**Comment by MLNW** [comment]
Wow, after spending a lot of time trying to find my error I finally find this issue. The documentation to this day (v26.0.1) states that the endpoint would return subGroups. Adding an empty `search` parameter fixes the issue but is very counter intuitive. Please add documentation to the API or fix the obvious bug.

A breaking change that has not been documented or addressed in two major versions like this really makes one reconsider using Keycloak.

**Comment by ahus1** [comment]
Re-opening, as updating the docs doesn't fix the original problem that this is a surprising behavior.

**Comment by pedroigor** [comment]
@RichieB2B It is the expected behavior and you are all right about the lack of information about this change in the release notes.

The changes in https://github.com/keycloak/keycloak/pull/36022 should help to clarify that now.

**Comment by pedroigor** [comment]
I'm also a bit confused about the `populateHierarchy` parameter. It won't populate the hierarchy for top-level groups.

Perhaps that is what is bringing more confusion. This parameter should default to `false` and only populate hierarchies when explicitly requested.

**Comment by pedroigor** [comment]
IIRC, one of the reasons for preventing returning subgroups when returning groups without a search parameter is that by default only top-level groups are returned. A database with lot of groups would potentially block and impact the server runtime.

I think we can consider fixing the semantics for `populateHierarchy` as previously mentioned and also add parameters to allow clients to specify how deep the subgroups should be returned.

**Comment by stianst** [comment]
> Sorry I have to chime in. The keycloak admin API is probably one of the worst API's I have ever seen. Almost every field is optional and basically nothing is documented. In more cases than not it behaves differently than expected. Everything is trial and error, and it feels like you can not expect ANY consistency in responses between endpoints at all. This makes working with keycloak in strictly typed languages a true nightmare. I'm not writing this to just rant, but to press on that this is a serious issue.

I'm well aware of this, and completely share your opinion on this - I don't think it's something we can resolve though without introducing a completely new version of the API, which is something I'd love to do, but currently we just don't have the capacity.

**Comment by katrybalski** [comment]
@SebastianKunz try to use `keycloakClient.realm(realm).groups().query("*")`

It seems to be working and trim does nothing for `*`. Not sure if that impact performance somehow.

**Comment by rsp-kuk** [comment]
We ran into the same issue today when our service supplier updated to 26.4.2

- **admin/realms/{{realm}}/groups?search=&exact=false** returns a list of top-level-groups without any subGroups
- **admin/realms/{{realm}}/groups?search=%20&exact=false** returns a list of top-level-groups including the children (thx @SebastianKunz )

From the docs I'd unterstand that searching for an empty group name should return the hierarchy as well.

**Comment by olenotron** [comment]
shocking that it has been more than a year! since the issue was opened and it still wasn't fixed
