### ISSUE TITLE
Absolute Path Not Working for config-keystore

### ISSUE THREAD

**Issue by ncphins** [keycloak/keycloak#29329]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

I am trying to use an absolute path (on a Windows Server 2022 machine) for the  config-keystore parameter in the conf file. I have gotten it to work fine for a relative path, but that is not feasible in our case.

I have other absolute paths that are working fine for https-certificate-file and https-certificate-key-file for example.

I have tried several things:
config-keystore=${kc.home.dir}\\conf\\keystore.p12
Error: java.lang.IllegalArgumentException: SRCFG00034: URI Syntax invalid C:\Program Files\ACME\Keycloak\keycloak-24.0.3\bin\..\conf\keystore.p12

config-keystore=${kc.home.dir}/conf/keystore.p12
java.lang.IllegalArgumentException: SRCFG00034: URI Syntax invalid C:\Program Files\ACME\Keycloak\keycloak-24.0.3\bin\../conf/keystore.p12

config-keystore=C:/Users/username/Development/keystore.p12
or
config-keystore=C:\Users\username\Development\keystore.p12
java.lang.IllegalArgumentException: SRCFG00033: Scheme C not supported

In the last case, the "C" is the drive letter. If I change to D: I get scheme D is not supported.

Maybe I am doing something wrong? Not sure. I thought this would work like the other paths I am using on this same machine.

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

I would think I could put a relative Windows path in the conf file for the keystore same as I do for the http certs (for example).

https-certificate-file=C:/Users/username/Development/Keycloak/certs/na_acme_com.crt

### Actual behavior

I get different errors with the different ways I try to enter the path.

### How to Reproduce?

Have a Keystore in a folder on aWindows machine.
Try to put the complete/absolute path to that keystore in the keycloak.conf file.

config-keystore=C:/Development/keystore.p12

**Comment by mwasson74** [comment]
Same/similar issue here with v24.0.3. Searching the issues for SRCFG00034 returns https://github.com/keycloak/keycloak/issues/22185 but it claims it was fixed with v22.0.4.

**Comment by ncphins** [comment]
I looked at that issue as well. The difference there is the path in that case (C:\keystore.p12) is giving a different error then than what I see now.

The error in that issue for that path was "SRCFG00034: URI Syntax invalid C:\keystore.p12"
but in my case that path will generate a "SRCFG00033: Scheme C not supported".

I will go back to 22.0.4 and see if this worked there. Might narrow it down some.

**Comment by mwasson74** [comment]
>I have tried several things:
config-keystore=${kc.home.dir}\conf\keystore.p12
Error: java.lang.IllegalArgumentException: SRCFG00034: URI Syntax invalid C:\Program Files\ACME\Keycloak\keycloak-24.0.3\bin..\conf\keystore.p12

>config-keystore=${kc.home.dir}/conf/keystore.p12
java.lang.IllegalArgumentException: SRCFG00034: URI Syntax invalid C:\Program Files\ACME\Keycloak\keycloak-24.0.3\bin../conf/keystore.p12

It looks like at least those 2 give you the same SRCFG00034 🤷‍♂️ 

Please keep me/us posted. Any information you or Keycloak can provide would obviously be greatly appreciated 🙏

**Comment by ncphins** [comment]
Here is what I found based on a quick test.

I had the following in the conf file: config-keystore=C:/Users/username/Development/keystore.p12

For the test, I created a new db schema for the test, dropped the identical conf file in the folder, ran a build, and ran in production mode. I verified the db schema was created properly after startup and saw no errors related to the keystore in the log.

23.0.0 - works (the keystore is read and I connected/created to the database fine)
23.0.4 - works (the keystore is read and I connected/created to the database fine)
23.0.7 - works (the keystore is read and I connected/created to the database fine)
24.0.0 - fails with the "SRCFG00033: Scheme C not supported"

**Comment by Pepo48** [comment]
Thanks for the report. Based on my analysis this was indeed re-introduced in https://github.com/keycloak/keycloak/pull/24811, but meanwhile it was already fixed within https://github.com/keycloak/keycloak/pull/25333. 

Have you tried to reproduce this behaviour with the Keycloak nightly release? I can confirm that specifying an absolute path to to a keystore, which is then used as an configuration source, works on my Windows 11 (23H2) machine.

cc: @vmuzikar

**Comment by Pepo48** [comment]
@ncphins no worries, thanks for raising the attention, the bug was indeed in the codebase and it might be still relevant when it comes to backporting the fix, so after all it wasn't waste of time.

Thanks for the collaboration and all the additional info provided above.

**Comment by vmuzikar** [comment]
I'm going to reopen this issue based on the current state:
* The issue was already fixed in main (in time for Keycloak 25) as a side effect of #25333. However, we're missing a test for it so it will be added in .
* The issue is still present in 24. We cannot backport #25333 due to its complexity and risk of regressions, so 24 will require a tailored fix.

**Comment by mwasson74** [comment]
@vmuzikar excuse me for my lack of knowledge regarding releases but I see the "release/24.0.6" label on this but I do not see a v24.0.6. Am I missing something? Also, do you know what versions of v24 this has been fixed in? Thank you!
