### ISSUE TITLE
Certificates do not conform to algorithm constraints

### ISSUE THREAD

**Issue by souravkm777** [keycloak/keycloak#30164]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Microsoft Azure has updated Azure Database for PostgreSQL Flexible Server to use TLS certificates [from Digicert Global Root CA to Microsoft RSA Root Certificate](https://aka.ms/postgresflextlscertdownload) Authority 2017
![image](https://github.com/keycloak/keycloak/assets/40356941/1f3df5b2-198f-4ce4-9e45-2cf5e5c91324)

We have recently restarted our Keycloak in Dev environment and after that it fails to start. The keycloak is running as a Pod on Azure kubernetes services.
Below is the error  log:

ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: SSL error: Certificates do not conform to algorithm constraints
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Certificates do not conform to algorithm constraints
 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Certificates do not conform to algorithm constraints
 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Algorithm constraints check failed on signature algorithm: SHA1withRSA

We suspect this started after the change from Microsoft and not sure how to fix that ourselves. Although the possible solution could be to add the new CA root to Keycloak's trusted root but need help with that.

### Version

23.0.4.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak pod should start normally after a resatrt

### Actual behavior

CrashLoopBackOff with error mentioned above

### How to Reproduce?

Everytime we restart we get the same error message for issue with connecting to the Postgresql flexible server. 

### Anything else?

N/A

**Comment by souravkm777** [comment]
Is there a way to allow Keycloak trust new CA provided by Microsoft?

**Comment by souravkm777** [comment]
Can you confirm if Keycloak uses certificate pinning while connecting to databases?

**Comment by souravkm777** [comment]
We have updated Keycloak to  version 24.0.5.0 but still has the same issue. The POD is not coming up so we are not able to update Java config. All other applications run fine after Microsoft has added the new root CA in Postgresql flexible offering and only Keycloak fails to connect. Really need help in getting this fixed.

**Comment by shawkins** [comment]
SHA1withRSA is likely no longer supported by default with Java 17. You can check the /etc/crypto-policies/back-ends/java.config - it should mention SHA1 as a disabled algorithm. You may need to custom image with a modified /etc/crypto-policies/back-ends/java.config file to support a legacy cert.

**Comment by souravkm777** [comment]
Just to add more context:
Keycloak was running fine with Azure Postgresql Flexible server(with SHA1 Digicert CA) until Microsoft updated the Postgresql flexible offerings with Microsoft CA (SHA384). 
Since the Pod doesnot come up we are not able to change the JAVA config for Keycloak.

**Comment by shawkins** [comment]
~priority-low

**Comment by raman-khrapavitski** [comment]
Are there some workarounds? I have tried this [https://learn.microsoft.com/en-us/azure/mysql/flexible-server/how-to-connect-tls-ssl#connect-using-mysql-command-line-client-with-tlsssl](guide), but shill get this error.

**Comment by souravkm777** [comment]
@raman-khrapavitski : We tried the same earlier but that did not work. We created a new instance of postgresql flexible server in Azure which comes with SHA2 certificate and our issue was resolved.

**Comment by jord1e** [comment]
> @raman-khrapavitski : We tried the same earlier but that did not work. We created a new instance of postgresql flexible server in Azure which comes with SHA2 certificate and our issue was resolved.

Thank you, this led me to a temporary solution.

See also https://github.com/Azure/azure-postgresql/issues/112

A bit of a bitter pill to swallow, but I circumvented creating a new instance by just enabling `SHA1` again for now:


```dockerfile
FROM quay.io/keycloak/keycloak:25.0.2

COPY --chown=keycloak:keycloak --from=builder /opt/keycloak/ /opt/keycloak/

# https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl
# https://github.com/keycloak/keycloak/issues/17606#issuecomment-1631115584
COPY --from=digicert /app/DigiCertGlobalRootCA.crt.pem /opt/keycloak/.postgresql/root.crt

# Our instance of PostgreSQL only has SHA1 certificates (for now)
# See https://github.com/keycloak/keycloak/issues/30164#issuecomment-2260625118
USER root
RUN ["sed", "-i", "s/SHA1, //g", "/usr/share/crypto-policies/DEFAULT/java.txt"]
# https://github.com/keycloak/keycloak/blob/36a141007ec12156c70ee00a55958114e60dd4f6/quarkus/container/Dockerfile#L34
USER 1000

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

Also

```dockerfile
ENV KC_DB_URL_PROPERTIES="?sslmode=verify-full"
```

When building the custom image, as referenced by the linked MS docs

Note that the reference to `DigiCertGlobalRootCA.crt.pem` comes from https://github.com/keycloak/keycloak/issues/17606#issuecomment-1631115584. It might also help some people.

**Comment by NicSalmonFR** [comment]
@souravkm777 could you please inform us which SHA2 certificate you got? I assume that uploading this cert would probably be sufficient to resolve the issue.

**Comment by sramkumars** [comment]
As a temporary solution, have used volumes to override the java.config file. No custom builds required.

**Comment by TideSupreme** [comment]
We had two environments on Azure running Keycloak with Postgres. One of those environments had the old certificate with the SHA1withRSA signature while the other had the newer signature. We had the "fix" on both environments for the past year. We've now retested (without spawning new postgres instances) and it seems Microsoft upgraded all their postgres certificates. 
I believe this issue is now resolved on Azure - and I recommend others to test and remove the problematic `sed -i s/SHA1` workaround (which was the only thing that worked for us). Downloading the DigiCertGlobalRootCA certificate isn't necessary anymore either.

**Comment by sharif997** [comment]
@jord1e Could you please paste all of the Dockerfile you are using, in your file you are mentioning "Copy From Builder" could you paste the builder part as well!

**Comment by jord1e** [comment]
Hi @sharif997 , this is our current config (excluding custom provider/configuration):

I'm hoping that Azure updates the certificate soon :(

```dockerfile
FROM quay.io/curl/curl:latest AS digicert

# To make it easier to reference the certificate location in the next stage
WORKDIR /app

RUN curl https://dl.cacerts.digicert.com/DigiCertGlobalRootCA.crt.pem -o DigiCertGlobalRootCA.crt.pem

FROM quay.io/keycloak/keycloak:26.1.0 AS builder

# See build options here: https://www.keycloak.org/server/containers
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
# Database configuration
ENV KC_DB=postgres
# See certificate installation in next stage (required fore Azure PostgreSQL Flexible Server)
ENV KC_DB_URL_PROPERTIES="?sslmode=verify-full"
# We only enable some features we (might) need
ENV KC_FEATURES=account-api,account,admin-api,admin,authorization,ciba,client-policies,client-secret-rotation,device-flow,docker,impersonation,login:v2,par,preview,recovery-codes,step-up-authentication,token-exchange,update-email

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build


FROM quay.io/keycloak/keycloak:26.1.0

COPY --chown=keycloak:keycloak --from=builder /opt/keycloak/ /opt/keycloak/

# https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl
# https://github.com/keycloak/keycloak/issues/17606#issuecomment-1631115584
COPY --from=digicert /app/DigiCertGlobalRootCA.crt.pem /opt/keycloak/conf/truststores/postgresql.pem

# Our instance of PostgreSQL only has SHA1 certificates (for now)
# See https://github.com/keycloak/keycloak/issues/30164#issuecomment-2260625118
USER root
RUN sed -i "s/SHA1, //g" /usr/share/crypto-policies/DEFAULT/java.txt \
 && sed -i "s/SHA1withRSA, //g" /usr/share/crypto-policies/DEFAULT/java.txt
# https://github.com/keycloak/keycloak/blob/36a141007ec12156c70ee00a55958114e60dd4f6/quarkus/container/Dockerfile#L34
USER 1000

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

Hope it helps

**Comment by jarek-jpa** [comment]
ok, in my situation the Azure PostgreSQL Flexible Server is still presenting one certificate with SHA1 in its chain (you can check it with `openssl s_client -connect <servername>.database.azure.com:5432 -starttls postgres -showcerts`)

1) Server Certificate: CN=servername.database.azure.com - sha256WithRSAEncryption
2) Intermediate Certificate: CN=DigiCert SHA2 Secure Server CA - sha256WithRSAEncryption
3) Root Certificate: CN=DigiCert Global Root CA - sha1WithRSAEncryption

this seems to make a problem for Keycloak 26 sitting on Java21 (`Algorithm constraints check failed on signature algorithm: SHA1withRSA`) (Java17 works). no solution with adding certificates to root.crt seem to work.

**Comment by jord1e** [comment]
The chain on our Azure PostgreSQL Flexible Server deployment is
1. CN = xxxx.database.azure.com / RSA-SHA256
2. CN = DigiCert SHA2 Secure Server CA / RSA-SHA256
3. CN = DigiCert Global Root CA / RSA-SHA1

Which looks to be the same. Are you sure that you built the CUSTOM image correctly and deployed the correct tag to your infra?

I'm sorry, I can't help you further than this, the Dockerfile above works for me

The `quay.io/keycloak/keycloak:26.1.0` runs on JDK 21:
```
sh-5.1$ java -version
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11-LTS, mixed mode, sharing)
```

Do note that if you don't use the `quay.io/keycloak/keycloak:26.1.0` image the path to crypto-policies might be different, it took me quite some time to figure out the correct location, but it works on the Dockerfile above

Good luck 😅

**Comment by jarek-jpa** [comment]
thanks for confirmation @jord1e . yes, finally I took the approach with re-allowing SHA1* ciphers (`sed -i` you mention above), and it works. thanks for specific instructions.

still my concern is how to get it working without lowering security standards (aka: "what did MS meant with updating their certificates if the root ca still uses sha-1". do I miss some point here?)

**Comment by jord1e** [comment]
The current SHA1 root certificate will be replaced gradually, although the message about this has been there for literal months on my deployment, no idea when it actually happens:

![Image](https://github.com/user-attachments/assets/1e813eab-7723-41cd-ab6b-998e4dfc6f99)

The new `Microsoft RSA Root Certificate Authority 2017` uses the SHA384-RSA cipher:

![Image](https://github.com/user-attachments/assets/ccd86dd1-c7cd-4c6b-a330-f8f6ec2e882c)

Its a bit of a sham because new Flexible Server deployments won't have the same problem as people confronted with this issue

Note that the other certificate that Flexible Server might use (`DigiCert Global Root G2`) uses SHA256, so the issue only really exists until Microsoft finally removes `DigiCert Global Root CA` from OLD deployments, which I can't find a definite date for

**Comment by shawkins** [comment]
Reviewed the most recent comments. The workaround of modifying the crypto-policies remains the solution for those affected. At this point we can simply close this issue - the number of users affected over time will continue to drop, and we don't in general want to document a solution that weakens the crypto policies.
