### ISSUE TITLE
NoSuchFileException with cert paths on Windows

### ISSUE THREAD

**Issue by crystalgreen** [keycloak/keycloak#31019]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

A similar issue as in #23217 occurs in v25.0.1 after working in v24. It seems the bug got reintroduced.
An invalid path results when using `${kc.home.dir}` on Windows:

> java.nio.file.NoSuchFileException: D:Dir1Dir2Dir3keyCloakbin..\..\..\cert\cert.pem

The issue might be unrelated to `${kc.home.dir}` because it also fails if pass the setting via command line and not via config file:

```
SET cert_file=%DIRNAME%..\..\..\TLS\cert.pem
SET key_file=%DIRNAME%..\..\..\TLS\key.pem
kc.bat start --https-certificate-file %cert_file% --https-certificate-key-file %key_file%
```
If `%cert_file%` contains backslashes, I get the error 

> java.nio.file.NoSuchFileException: D:Dir1Dir2Dir3keyCloakbin......certcert.pem

Workaround: replacing all backslashes by slashes causes this error to vanish.

```
SET cert_file=!cert_file:\=/!
SET key_file=!key_file:\=/!
```

PS: Trying to pass these settings via environment variables yields another error and I'm too lazy to open another issue.

```
SET KC_https_certificate_file=%cert_file%
SET KC_https_certificate_key_file=%key_file%
kc.bat start 
```
> io.quarkus.runtime.configuration.ConfigurationException: Failed to read configuration properties
> ...
> Caused by: java.lang.NullPointerException: Cannot invoke "io.smallrye.config.ConfigValue.getValue()" because the return value of "io.smallrye.config.ConfigSourceInterceptorContext.proceed(String)" is null

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Windows paths with backslashes should be handled correctly.

### Actual behavior

Error at start:

> java.nio.file.NoSuchFileException: D:Dir1Dir2Dir3keyCloakbin..\..\..\cert\cert.pem

### How to Reproduce?

Use Windows and try a https-certificate-file configuration similar to mine, containing ${kc.home.dir}.

### Anything else?

See my old issue  #23217.

**Comment by Pepo48** [comment]
I would say that this is related to a different [issue](https://github.com/keycloak/keycloak/pull/30101) that we resolved in the past and that was related to the changes in Picocli.java class regarding PropertyMappers' handling and sanitization. 

This time it is not about an absolute path but the ${kc.home.dir} expansion. The exception is caught [here](https://github.com/quarkusio/quarkus/blob/3.8/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/options/HttpServerOptionsUtils.java#L404) as the expanded part is typically without backslashes so the path is incorrect and the certificate cannot be found and processed.

I did not find the solution yet as the manual initializaition of the configuration as we did in the backport via getConfig() does not help here. 

I will definitely look into this one in more detail.

cc @vmuzikar - can [this part](https://github.com/keycloak/keycloak/blob/bf1248d06261f0c0b0139a24d3ce298ede023e03/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java#L95) potentially cause the problems? HTTP property mapper definitely reaches this point with ${kc.home.dir} not expanded.

**Comment by vmuzikar** [comment]
> cc @vmuzikar - can [this part](https://github.com/keycloak/keycloak/blob/bf1248d06261f0c0b0139a24d3ce298ede023e03/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java#L95) potentially cause the problems? HTTP property mapper definitely reaches this point with ${kc.home.dir} not expanded.

Yes, looks like the expression might not get expanded correctly here. But not sure, it needs more investigation.

If I understand correctly, you were able to reproduce the issue. I'm bringing it out of triage then.

~priority-important

**Comment by Pepo48** [comment]
Hi @crystalgreen,

can you please try to reproduce it with the latest `upstream/main` in your environment? I revisited this issue today and tried it on my Windows 11 VM (ARM64) this time.
Given the following configuration:
```
https-certificate-file=${kc.home.dir}/conf/server.crt.pem
https-certificate-key-file=${kc.home.dir}/conf/server.key.pem
```
my Keycloak instance started successfully.
![image](https://github.com/user-attachments/assets/d51b9edd-39ce-4ffb-ac4f-687a0fdff671)

Let me know in any case.
Thanks.

**Comment by Pepo48** [comment]
I can additionally confirm that the latest nightly worked flawlessly even on my personal W11 23H2 machine. The issue has been most likely resolved by one of the recent Quarkus upgrades, specifically with the `quarkus-vertx-http` from 3.8 (then) to 3.13 (now). There was[ a revamp of logic](https://github.com/quarkusio/quarkus/commit/194c87e40a21f98ca040a62bf86e9da500bb9a3b#diff-cc803c7a26d10e6a74ae09f2a38d09714b6133593a4f6c04c299b40503b193a0) between these two versions.

**Comment by Pepo48** [comment]
Hi @crystalgreen, for the purpose of testing the latest fixes in the distribution within your environment, you can just download the Keycloak nightly build.

**Comment by Pepo48** [comment]
The unavailability of the distribution zip was caused by a bug. Now it should be ok, please, try to download it again.

**Comment by crystalgreen** [comment]
I managed to successfully run the nightly build on Win11. I confirm: this issue seems resolved. I tried with a cert path like
`https-certificate-file=${kc.home.dir}/../TLS/cert.pem`.

IMO you can close the issue.

**Comment by crystalgreen** [comment]
Unfortunately, I can still reproduce the issue on the nightly, when I set either `health-enabled=true` or `metrics-enabled=true`.

Here the error after start with `./kc.bat start-dev --verbose`. 

```
2024-09-06 16:59:38,906 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.nio.file.NoSuchFileException: D:testskeycloakkeycloak-999.0.0-SNAPSHOTbin..\..\TLS\cert.pem
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:159)
        at io.quarkus.vertx.http.runtime.options.HttpServerOptionsUtils.getFileContent(HttpServerOptionsUtils.java:411)
        at io.quarkus.vertx.http.runtime.options.TlsUtils.createPemKeyCertOptions(TlsUtils.java:186)
        at io.quarkus.vertx.http.runtime.options.TlsUtils.computeKeyStoreOptions(TlsUtils.java:43)
        at io.quarkus.vertx.http.runtime.options.HttpServerOptionsUtils.applySslConfigToHttpServerOptions(HttpServerOptionsUtils.java:158)
        at io.quarkus.vertx.http.runtime.options.HttpServerOptionsUtils.createSslOptionsForManagementInterface(HttpServerOptionsUtils.java:209)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeManagementInterface(VertxHttpRecorder.java:662)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:829)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:348)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1753087980.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1753087980.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:141)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:138)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:101)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
```

Probably unrelated: I had to set `http-management-port=9003` as my port 9000 is already in use. For that, see also [here](https://github.com/keycloak/keycloak/issues/31134).
If I disable my https cert paths then it works with health/metrics enabled.

**Comment by crystalgreen** [comment]
@Pepo48 Any thoughts about my above observation? Can you reproduce it?
