### ISSUE TITLE
Keycloak Docker-Image hard crash on MacOS 15.2 with M4

### ISSUE THREAD

**Issue by JrTimha** [keycloak/keycloak#36008]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

Cannot launch any ARM-based Keycloak Docker Image on MacOS 15.2 with M4 Pro Chip from quay.io/keycloak/keycloak with a Keycloak version above 25.0. I tested Keycloak 25 and Keycloak 26 (.2, .5 and .7). This is a specific issue only reproducable with MacOS 15.2, M4 Chip and in a Docker-Container with OpenJDK 21 or 23. Look at the references below for necessary informations.

It would be great if a nightly build of the arm-based Keycloak would use a newer OpenJDK 21 version. Because at the moment it is not usable with my setup.

### Version

26.0.7 (nightly) or any other version with JDK 21

### Regression

- [ ] The issue is a regression

### Expected behavior

My expected behavior is that I can start a Keycloak container with Docker Desktop with images from quay.io.

### Actual behavior

Error: 

```0.135 #
0.135 # A fatal error has been detected by the Java Runtime Environment:
0.135 #
0.135 #  SIGILL (0x4) at pc=0x0000ffff8b93fc5c, pid=1, tid=7
0.135 #
0.135 # JRE version:  (21.0.5+11) (build )
0.135 # Java VM: OpenJDK 64-Bit Server VM (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
0.135 # Problematic frame:
0.135 # j  java.lang.System.registerNatives()V+0 java.base
0.135 #
0.135 # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
0.135 #
0.137 # An error report file with more information is saved as:
0.137 # /opt/keycloak/hs_err_pid1.log
0.143 [0.037s][warning][os] Loading hsdis library failed
0.146 #
0.146 # The crash happened outside the Java Virtual Machine in native code.
0.146 # See problematic frame for where to report the bug.
0.146 #
0.146 
[+] Running 0/1curred during error reporting (), id 0x5, SIGTRAP (0x5) at pc=0x0000ffffa24c6070]

/opt/keycloak/bin/kc.sh: line 169:    87 Aborted                 'java' -Dkc.config.build-and-exit=true -Djava.util.concurrent.ForkJoinPool.common.threadFactory=io.quarkus.bootstrap.forkjoin.QuarkusForkJoinWorkerThreadFactory '-XX:MetaspaceSize=96M' '-XX:MaxMetaspaceSize=256m' '-Dfile.encoding=UTF-8' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dstdout.encoding=UTF-8' '-Dstderr.encoding=UTF-8' '-XX:+ExitOnOutOfMemoryError' '-Djava.security.egd=file:/dev/urandom' '-XX:+UseG1GC' '-XX:FlightRecorderOptions=stackdepth=512' '-XX:MaxRAMPercentage=70' '-XX:MinRAMPercentage=70' '-XX:InitialRAMPercentage=50' '--add-opens=java.base/java.util=ALL-UNNAMED' '--add-opens=java.base/java.util.concurrent=ALL-UNNAMED' '--add-opens=java.base/java.security=ALL-UNNAMED' '-Duser.language=en' '-Duser.country=US' '-Dkeycloak.profile.feature.upload_scripts=enabled' -Dkc.home.dir='/opt/keycloak/bin/..' -Djboss.server.config.dir='/opt/keycloak/bin/../conf' -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dpicocli.disable.closures=true -Dquarkus-log-max-startup-records=10000 -cp '/opt/keycloak/bin/../lib/quarkus-run.jar' io.quarkus.bootstrap.runner.QuarkusEntryPoint 'start' '--import-realm' '--verbose'
```

### How to Reproduce?

Use a Mac with M4 Chip, update to MacOS 15.2 and all Docker-Images with OpenJDK 21 or 23 can't start.

Just try to start it in a compose .yaml:

```
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ['start', '--import-realm', '--verbose']
    depends_on:
      - "KeycloakDB"
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      KC_DB: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://KeycloakDB:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME: http://localhost:8180
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - local
    volumes:
      - ./your-realm.json:/opt/keycloak/data/import/your-realm.json
```

### Anything else?

There are workarounds and similar issues in other GitHub-Repositories mentioned. This error is fixed with a newer JDK Version. There are also workarounds mentioned in other issues, where people are starting the .jar with -XX:UseSVE=0.

https://github.com/openjdk/jdk21u-dev/pull/1222
https://bugs.openjdk.org/browse/JDK-8345296
https://github.com/corretto/corretto-21/issues/85

**Comment by Qulence** [comment]
Cannot launch Keycloak Docker Image on MacOS 15.2 with M4 Pro Chip

my docker-compose.yml:

```
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak_container
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./src/main/resources/keycloak:/opt/keycloak/data/import
    ports:
      - "7080:8080"
```

Error:
```
2024-12-20 05:59:07 #
2024-12-20 05:59:07 # A fatal error has been detected by the Java Runtime Environment:
2024-12-20 05:59:07 #
2024-12-20 05:59:07 #  SIGILL (0x4) at pc=0x0000ffff7b93fc5c, pid=81, tid=82
2024-12-20 05:59:07 #
2024-12-20 05:59:07 # JRE version:  (21.0.5+11) (build )
2024-12-20 05:59:07 # Java VM: OpenJDK 64-Bit Server VM (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
2024-12-20 05:59:07 # Problematic frame:
2024-12-20 05:59:07 # j  java.lang.System.registerNatives()V+0 java.base
2024-12-20 05:59:07 #
2024-12-20 05:59:07 # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
2024-12-20 05:59:07 #
2024-12-20 05:59:07 # An error report file with more information is saved as:
2024-12-20 05:59:07 # /tmp/hs_err_pid81.log
2024-12-20 05:59:07 [0.013s][warning][os] Loading hsdis library failed
2024-12-20 05:59:07 #
2024-12-20 05:59:07 # The crash happened outside the Java Virtual Machine in native code.
2024-12-20 05:59:07 # See problematic frame for where to report the bug.
2024-12-20 05:59:07 #
2024-12-20 05:59:07 /opt/keycloak/bin/kc.sh: line 169:    81 Aborted                 'java' -Dkc.config.build-and-exit=true -Djava.util.concurrent.ForkJoinPool.common.threadFactory=io.quarkus.bootstrap.forkjoin.QuarkusForkJoinWorkerThreadFactory '-XX:MetaspaceSize=96M' '-XX:MaxMetaspaceSize=256m' '-Dfile.encoding=UTF-8' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dstdout.encoding=UTF-8' '-Dstderr.encoding=UTF-8' '-XX:+ExitOnOutOfMemoryError' '-Djava.security.egd=file:/dev/urandom' '-XX:+UseG1GC' '-XX:FlightRecorderOptions=stackdepth=512' '-XX:MaxRAMPercentage=70' '-XX:MinRAMPercentage=70' '-XX:InitialRAMPercentage=50' '--add-opens=java.base/java.util=ALL-UNNAMED' '--add-opens=java.base/java.util.concurrent=ALL-UNNAMED' '--add-opens=java.base/java.security=ALL-UNNAMED' '-Duser.language=en' '-Duser.country=US' -Dkc.home.dir='/opt/keycloak/bin/..' -Djboss.server.config.dir='/opt/keycloak/bin/../conf' -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dpicocli.disable.closures=true -Dquarkus-log-max-startup-records=10000 -cp '/opt/keycloak/bin/../lib/quarkus-run.jar' io.quarkus.bootstrap.runner.QuarkusEntryPoint --profile=dev start-dev '--import-realm'

```

**Comment by driesvancraen** [comment]
Specifying the platform did the trick for me:

`docker run --platform linux/amd64 -p 8080:8080 \
  -e KC_BOOTSTRAP_ADMIN_USERNAME=admin \
  -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin \
  quay.io/keycloak/keycloak:26.0.7 start-dev`

**Comment by malouda92** [comment]
As @driesvancraen advise
have had to specify the platform
docker-compose.yml:
`  keycloak:
    image: quay.io/keycloak/keycloak:latest
    platform: linux/amd64
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://database:5432/keycloak"
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}`
it's solved

**Comment by derekelewis** [comment]
Also affects OpenShift Local on MacOS when installing the operator

**Comment by jonkoops** [comment]
Is there any action we can take as the Keycloak project here? This seems to be a deeper issue in the JDK that should be resolved there and not in individual projects that depend on it.

**Comment by JrTimha** [comment]
To resolve this issue, consider updating the JDK to a newer version, where the problem has been addressed.

Alternatively, for Keycloak Docker setups, you can use the -XX:UseSVE=0 JVM option as a quick fix. This approach is preferable to using an amd64 image on an arm64 setup, as it avoids adding a simulation layer.

**Comment by jonkoops** [comment]
Our image [is based on](https://github.com/keycloak/keycloak/blob/f41ce7177c49a3fc47c1e874af4759ca0ff0a258/quarkus/container/Dockerfile#L20) the `java-21-openjdk-headless` package of the [Red Hat Universal Base Image 9](https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e?container-tabs=overview) (UBI-9).If there are fixed versions available of this package then I would recommend reaching out to the team responsible for this image to get a fix in so it trickles down automatically.

**Comment by jonkoops** [comment]
Closing this as I believe this should be automatically fixed as we do the next patch release (if the fix is in the base image), we expect this to happen in early January.

**Comment by iqgeo2013** [comment]
The issue still persist. 

2025-01-31 16:57:46 # An error report file with more information is saved as:
2025-01-31 16:57:46 # /tmp/hs_err_pid80.log
2025-01-31 16:57:46 [0.008s][warning][os] Loading hsdis library failed
2025-01-31 16:57:46 #
2025-01-31 16:57:46 # The crash happened outside the Java Virtual Machine in native code.
2025-01-31 16:57:46 # See problematic frame for where to report the bug.
2025-01-31 16:57:46 #
2025-01-31 16:57:50 #
2025-01-31 16:57:50 # A fatal error has been detected by the Java Runtime Environment:
2025-01-31 16:57:50 #
2025-01-31 16:57:50 #  SIGILL (0x4) at pc=0x0000ffff9b867c5c, pid=80, tid=81
2025-01-31 16:57:50 #
2025-01-31 16:57:50 # JRE version:  (21.0.5+11) (build )
2025-01-31 16:57:50 # Java VM: OpenJDK 64-Bit Server VM (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
2025-01-31 16:57:50 # Problematic frame:
2025-01-31 16:57:50 # j  java.lang.System.registerNatives()V+0 java.base
2025-01-31 16:57:50 #
2025-01-31 16:57:50 # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
2025-01-31 16:57:50 #
2025-01-31 16:57:50 # An error report file with more information is saved as:
2025-01-31 16:57:50 # /tmp/hs_err_pid80.log
2025-01-31 16:57:50 [0.011s][warning][os] Loading hsdis library failed
2025-01-31 16:57:50 #
2025-01-31 16:57:50 # The crash happened outside the Java Virtual Machine in native code.
2025-01-31 16:57:50 # See problematic frame for where to report the bug.

docker-compose.yaml 

version: '3.8'

networks:
  ffm_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.101.0/24

services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: ffm
    networks:
      - ffm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ffm"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/ffm
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
    volumes:
      - ./keycloak_data:/opt/keycloak/data
      - ./keycloak_themes/fsf:/opt/keycloak/themes/fsf
    command: ["start-dev", "--db=postgres"]
    depends_on:
      - postgres
    networks:
      - ffm_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/auth/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 5

**Comment by fbuetler** [comment]
Setting the JVM option `-XX:UseSVE=0` is a workaround.

**Comment by iqgeo2013** [comment]
is working 
JAVA_OPTS: -XX:UseSVE=0

**Comment by domdorn** [comment]
I'm hitting this Issue with Quarkus.. I only added 
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc</artifactId>
        </dependency>
```
to my pom and now the application does not start up anymore because Quarkus tries to start that container. I have not found a way to tell quarkus to use another architecture!

This is the stack trace I get:
```
org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: org.testcontainers.containers.GenericContainer$$Lambda/0x000000700162a0f0 expected the predicate to return <true> but it returned <false> for input of <InspectContainerResponse(args=[start, --http-enabled=true, --hostname-strict=false, --spi-user-profile-declarative-user-profile-config-file=/opt/keycloak/upconfig.json], config=ContainerConfig(attachStderr=false, attachStdin=false, attachStdout=false, cmd=[start, --http-enabled=true, --hostname-strict=false, --spi-user-profile-declarative-user-profile-config-file=/opt/keycloak/upconfig.json], domainName=, entrypoint=[/opt/keycloak/bin/kc.sh], env=[KC_BOOTSTRAP_ADMIN_USERNAME=admin, KC_BOOTSTRAP_ADMIN_PASSWORD=admin, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, LANG=en_US.UTF-8, KC_RUN_IN_CONTAINER=true], exposedPorts=[8080/tcp, 8443/tcp, 9000/tcp], hostName=83a9530551c8, image=quay.io/keycloak/keycloak:26.0.7, labels={architecture=aarch64, build-date=2024-12-02T07:58:58Z, com.redhat.build-host=, com.redhat.component=, com.redhat.license_terms=, description=Keycloak Server Image, distribution-scope=public, io.buildah.version=1.38.0-dev, io.k8s.description=Keycloak Server Image, io.k8s.display-name=Keycloak Server, io.openshift.expose-services=, io.openshift.tags=keycloak security identity, maintainer=https://www.keycloak.org/, name=keycloak, org.opencontainers.image.created=2024-12-03T07:16:32.656Z, org.opencontainers.image.description=, org.opencontainers.image.documentation=https://www.keycloak.org/documentation, org.opencontainers.image.licenses=Apache-2.0, org.opencontainers.image.revision=9dc36e6787c902eff4e74369e6a5fd3cd3798e1d, org.opencontainers.image.source=https://github.com/keycloak-rel/keycloak-rel, org.opencontainers.image.title=keycloak-rel, org.opencontainers.image.url=https://github.com/keycloak-rel/keycloak-rel, org.opencontainers.image.version=26.0.7, org.testcontainers=true, org.testcontainers.lang=java, org.testcontainers.sessionId=fa5d9dd9-7a17-4fc2-a0f7-07cd0b414641, org.testcontainers.version=1.20.4, quarkus-dev-service-keycloak=quarkus, release=, summary=Keycloak Server Image, url=https://www.keycloak.org/, vcs-ref=, vcs-type=git, vendor=https://www.keycloak.org/, version=26.0.7}, macAddress=null, networkDisabled=null, onBuild=null, stdinOpen=false, portSpecs=null, stdInOnce=false, tty=false, user=1000, volumes=null, workingDir=/, healthCheck=null), created=2025-02-23T16:50:19.482041419Z, driver=overlayfs, execDriver=null, hostConfig=HostConfig(binds=[], blkioWeight=0, blkioWeightDevice=null, blkioDeviceReadBps=null, blkioDeviceWriteBps=null, blkioDeviceReadIOps=null, blkioDeviceWriteIOps=null, memorySwappiness=null, nanoCPUs=0, capAdd=null, capDrop=null, containerIDFile=, cpuPeriod=0, cpuRealtimePeriod=0, cpuRealtimeRuntime=0, cpuShares=0, cpuQuota=0, cpusetCpus=, cpusetMems=, devices=null, deviceCgroupRules=null, deviceRequests=null, diskQuota=null, dns=null, dnsOptions=null, dnsSearch=null, extraHosts=[], groupAdd=null, ipcMode=shareable, cgroup=, links=[], logConfig=LogConfig(type=json-file, config={}), lxcConf=null, memory=786432000, memorySwap=1572864000, memoryReservation=0, kernelMemory=null, networkMode=bridge, oomKillDisable=null, init=null, autoRemove=false, oomScoreAdj=0, portBindings={8080/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@a50e240}, privileged=false, publishAllPorts=false, readonlyRootfs=false, restartPolicy=no, ulimits=null, cpuCount=0, cpuPercent=0, ioMaximumIOps=0, ioMaximumBandwidth=0, volumesFrom=[], mounts=null, pidMode=, isolation=null, securityOpts=null, storageOpt=null, cgroupParent=, volumeDriver=, shmSize=67108864, pidsLimit=null, runtime=runc, tmpFs=null, utSMode=, usernsMode=, sysctls=null, consoleSize=[0, 0], cgroupnsMode=private), hostnamePath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/hostname, hostsPath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/hosts, logPath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab-json.log, id=83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab, sizeRootFs=null, sizeRw=null, imageId=sha256:4388e2379b7e870a447adbe7b80bd61f5fbf04e925832b19669fda4957f05a81, mountLabel=, name=/strange_dijkstra, restartCount=0, networkSettings=NetworkSettings(bridge=, sandboxId=, hairpinMode=false, linkLocalIPv6Address=, linkLocalIPv6PrefixLen=0, ports={}, sandboxKey=, secondaryIPAddresses=null, secondaryIPv6Addresses=null, endpointID=, gateway=, portMapping=null, globalIPv6Address=, globalIPv6PrefixLen=0, ipAddress=, ipPrefixLen=0, ipV6Gateway=, macAddress=, networks={bridge=ContainerNetwork(ipamConfig=null, links=[], aliases=null, networkID=b12d07103a9d079b360311a1add86bb3cd704fb5226248c44d9642e76a971616, endpointId=, gateway=, ipAddress=, ipPrefixLen=0, ipV6Gateway=, globalIPv6Address=, globalIPv6PrefixLen=0, macAddress=)}), path=/opt/keycloak/bin/kc.sh, processLabel=, resolvConfPath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/resolv.conf, execIds=null, state=InspectContainerResponse.ContainerState(status=exited, running=false, paused=false, restarting=false, oomKilled=false, dead=false, pid=0, exitCode=134, error=, startedAt=2025-02-23T16:50:19.527575627Z, finishedAt=2025-02-23T16:50:19.627666086Z, health=null), volumes=null, volumesRW=null, node=null, mounts=[], graphDriver=GraphDriver(name=overlayfs, data=null), platform=linux)> within 5 seconds.
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.testcontainers.shaded.org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:691)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:708)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:458)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:415)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:441)
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:195)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Resulted in: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)
	... 18 more
Resulted in: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	... 16 more
Resulted in: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.0.7
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)
	... 15 more
Resulted in: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.0.7
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:245)
	... 10 more
Resulted in: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.0.7
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:245)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Resulted in: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.0.7
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:415)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:441)
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:195)
	... 10 more
Resulted in: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)
	... 15 more
Resulted in: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 16 more
Resulted in: org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: org.testcontainers.containers.GenericContainer$$Lambda/0x000000700162a0f0 expected the predicate to return <true> but it returned <false> for input of <InspectContainerResponse(args=[start, --http-enabled=true, --hostname-strict=false, --spi-user-profile-declarative-user-profile-config-file=/opt/keycloak/upconfig.json], config=ContainerConfig(attachStderr=false, attachStdin=false, attachStdout=false, cmd=[start, --http-enabled=true, --hostname-strict=false, --spi-user-profile-declarative-user-profile-config-file=/opt/keycloak/upconfig.json], domainName=, entrypoint=[/opt/keycloak/bin/kc.sh], env=[KC_BOOTSTRAP_ADMIN_USERNAME=admin, KC_BOOTSTRAP_ADMIN_PASSWORD=admin, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, LANG=en_US.UTF-8, KC_RUN_IN_CONTAINER=true], exposedPorts=[8080/tcp, 8443/tcp, 9000/tcp], hostName=83a9530551c8, image=quay.io/keycloak/keycloak:26.0.7, labels={architecture=aarch64, build-date=2024-12-02T07:58:58Z, com.redhat.build-host=, com.redhat.component=, com.redhat.license_terms=, description=Keycloak Server Image, distribution-scope=public, io.buildah.version=1.38.0-dev, io.k8s.description=Keycloak Server Image, io.k8s.display-name=Keycloak Server, io.openshift.expose-services=, io.openshift.tags=keycloak security identity, maintainer=https://www.keycloak.org/, name=keycloak, org.opencontainers.image.created=2024-12-03T07:16:32.656Z, org.opencontainers.image.description=, org.opencontainers.image.documentation=https://www.keycloak.org/documentation, org.opencontainers.image.licenses=Apache-2.0, org.opencontainers.image.revision=9dc36e6787c902eff4e74369e6a5fd3cd3798e1d, org.opencontainers.image.source=https://github.com/keycloak-rel/keycloak-rel, org.opencontainers.image.title=keycloak-rel, org.opencontainers.image.url=https://github.com/keycloak-rel/keycloak-rel, org.opencontainers.image.version=26.0.7, org.testcontainers=true, org.testcontainers.lang=java, org.testcontainers.sessionId=fa5d9dd9-7a17-4fc2-a0f7-07cd0b414641, org.testcontainers.version=1.20.4, quarkus-dev-service-keycloak=quarkus, release=, summary=Keycloak Server Image, url=https://www.keycloak.org/, vcs-ref=, vcs-type=git, vendor=https://www.keycloak.org/, version=26.0.7}, macAddress=null, networkDisabled=null, onBuild=null, stdinOpen=false, portSpecs=null, stdInOnce=false, tty=false, user=1000, volumes=null, workingDir=/, healthCheck=null), created=2025-02-23T16:50:19.482041419Z, driver=overlayfs, execDriver=null, hostConfig=HostConfig(binds=[], blkioWeight=0, blkioWeightDevice=null, blkioDeviceReadBps=null, blkioDeviceWriteBps=null, blkioDeviceReadIOps=null, blkioDeviceWriteIOps=null, memorySwappiness=null, nanoCPUs=0, capAdd=null, capDrop=null, containerIDFile=, cpuPeriod=0, cpuRealtimePeriod=0, cpuRealtimeRuntime=0, cpuShares=0, cpuQuota=0, cpusetCpus=, cpusetMems=, devices=null, deviceCgroupRules=null, deviceRequests=null, diskQuota=null, dns=null, dnsOptions=null, dnsSearch=null, extraHosts=[], groupAdd=null, ipcMode=shareable, cgroup=, links=[], logConfig=LogConfig(type=json-file, config={}), lxcConf=null, memory=786432000, memorySwap=1572864000, memoryReservation=0, kernelMemory=null, networkMode=bridge, oomKillDisable=null, init=null, autoRemove=false, oomScoreAdj=0, portBindings={8080/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@a50e240}, privileged=false, publishAllPorts=false, readonlyRootfs=false, restartPolicy=no, ulimits=null, cpuCount=0, cpuPercent=0, ioMaximumIOps=0, ioMaximumBandwidth=0, volumesFrom=[], mounts=null, pidMode=, isolation=null, securityOpts=null, storageOpt=null, cgroupParent=, volumeDriver=, shmSize=67108864, pidsLimit=null, runtime=runc, tmpFs=null, utSMode=, usernsMode=, sysctls=null, consoleSize=[0, 0], cgroupnsMode=private), hostnamePath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/hostname, hostsPath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/hosts, logPath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab-json.log, id=83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab, sizeRootFs=null, sizeRw=null, imageId=sha256:4388e2379b7e870a447adbe7b80bd61f5fbf04e925832b19669fda4957f05a81, mountLabel=, name=/strange_dijkstra, restartCount=0, networkSettings=NetworkSettings(bridge=, sandboxId=, hairpinMode=false, linkLocalIPv6Address=, linkLocalIPv6PrefixLen=0, ports={}, sandboxKey=, secondaryIPAddresses=null, secondaryIPv6Addresses=null, endpointID=, gateway=, portMapping=null, globalIPv6Address=, globalIPv6PrefixLen=0, ipAddress=, ipPrefixLen=0, ipV6Gateway=, macAddress=, networks={bridge=ContainerNetwork(ipamConfig=null, links=[], aliases=null, networkID=b12d07103a9d079b360311a1add86bb3cd704fb5226248c44d9642e76a971616, endpointId=, gateway=, ipAddress=, ipPrefixLen=0, ipV6Gateway=, globalIPv6Address=, globalIPv6PrefixLen=0, macAddress=)}), path=/opt/keycloak/bin/kc.sh, processLabel=, resolvConfPath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/resolv.conf, execIds=null, state=InspectContainerResponse.ContainerState(status=exited, running=false, paused=false, restarting=false, oomKilled=false, dead=false, pid=0, exitCode=134, error=, startedAt=2025-02-23T16:50:19.527575627Z, finishedAt=2025-02-23T16:50:19.627666086Z, health=null), volumes=null, volumesRW=null, node=null, mounts=[], graphDriver=GraphDriver(name=overlayfs, data=null), platform=linux)> within 5 seconds.
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.testcontainers.shaded.org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:691)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:708)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:458)
	... 18 more

	at io.quarkus.builder.Execution.run(Execution.java:124)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:161)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:350)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:285)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:61)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:200)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:183)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:555)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:455)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:163)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:150)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221)
	at io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1591)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Resulted in: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.0.7
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:245)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Resulted in: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.0.7
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:415)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:441)
	at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:195)
	... 10 more
Resulted in: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)
	... 15 more
Resulted in: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 16 more
Resulted in: org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: org.testcontainers.containers.GenericContainer$$Lambda/0x000000700162a0f0 expected the predicate to return <true> but it returned <false> for input of <InspectContainerResponse(args=[start, --http-enabled=true, --hostname-strict=false, --spi-user-profile-declarative-user-profile-config-file=/opt/keycloak/upconfig.json], config=ContainerConfig(attachStderr=false, attachStdin=false, attachStdout=false, cmd=[start, --http-enabled=true, --hostname-strict=false, --spi-user-profile-declarative-user-profile-config-file=/opt/keycloak/upconfig.json], domainName=, entrypoint=[/opt/keycloak/bin/kc.sh], env=[KC_BOOTSTRAP_ADMIN_USERNAME=admin, KC_BOOTSTRAP_ADMIN_PASSWORD=admin, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, LANG=en_US.UTF-8, KC_RUN_IN_CONTAINER=true], exposedPorts=[8080/tcp, 8443/tcp, 9000/tcp], hostName=83a9530551c8, image=quay.io/keycloak/keycloak:26.0.7, labels={architecture=aarch64, build-date=2024-12-02T07:58:58Z, com.redhat.build-host=, com.redhat.component=, com.redhat.license_terms=, description=Keycloak Server Image, distribution-scope=public, io.buildah.version=1.38.0-dev, io.k8s.description=Keycloak Server Image, io.k8s.display-name=Keycloak Server, io.openshift.expose-services=, io.openshift.tags=keycloak security identity, maintainer=https://www.keycloak.org/, name=keycloak, org.opencontainers.image.created=2024-12-03T07:16:32.656Z, org.opencontainers.image.description=, org.opencontainers.image.documentation=https://www.keycloak.org/documentation, org.opencontainers.image.licenses=Apache-2.0, org.opencontainers.image.revision=9dc36e6787c902eff4e74369e6a5fd3cd3798e1d, org.opencontainers.image.source=https://github.com/keycloak-rel/keycloak-rel, org.opencontainers.image.title=keycloak-rel, org.opencontainers.image.url=https://github.com/keycloak-rel/keycloak-rel, org.opencontainers.image.version=26.0.7, org.testcontainers=true, org.testcontainers.lang=java, org.testcontainers.sessionId=fa5d9dd9-7a17-4fc2-a0f7-07cd0b414641, org.testcontainers.version=1.20.4, quarkus-dev-service-keycloak=quarkus, release=, summary=Keycloak Server Image, url=https://www.keycloak.org/, vcs-ref=, vcs-type=git, vendor=https://www.keycloak.org/, version=26.0.7}, macAddress=null, networkDisabled=null, onBuild=null, stdinOpen=false, portSpecs=null, stdInOnce=false, tty=false, user=1000, volumes=null, workingDir=/, healthCheck=null), created=2025-02-23T16:50:19.482041419Z, driver=overlayfs, execDriver=null, hostConfig=HostConfig(binds=[], blkioWeight=0, blkioWeightDevice=null, blkioDeviceReadBps=null, blkioDeviceWriteBps=null, blkioDeviceReadIOps=null, blkioDeviceWriteIOps=null, memorySwappiness=null, nanoCPUs=0, capAdd=null, capDrop=null, containerIDFile=, cpuPeriod=0, cpuRealtimePeriod=0, cpuRealtimeRuntime=0, cpuShares=0, cpuQuota=0, cpusetCpus=, cpusetMems=, devices=null, deviceCgroupRules=null, deviceRequests=null, diskQuota=null, dns=null, dnsOptions=null, dnsSearch=null, extraHosts=[], groupAdd=null, ipcMode=shareable, cgroup=, links=[], logConfig=LogConfig(type=json-file, config={}), lxcConf=null, memory=786432000, memorySwap=1572864000, memoryReservation=0, kernelMemory=null, networkMode=bridge, oomKillDisable=null, init=null, autoRemove=false, oomScoreAdj=0, portBindings={8080/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@a50e240}, privileged=false, publishAllPorts=false, readonlyRootfs=false, restartPolicy=no, ulimits=null, cpuCount=0, cpuPercent=0, ioMaximumIOps=0, ioMaximumBandwidth=0, volumesFrom=[], mounts=null, pidMode=, isolation=null, securityOpts=null, storageOpt=null, cgroupParent=, volumeDriver=, shmSize=67108864, pidsLimit=null, runtime=runc, tmpFs=null, utSMode=, usernsMode=, sysctls=null, consoleSize=[0, 0], cgroupnsMode=private), hostnamePath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/hostname, hostsPath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/hosts, logPath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab-json.log, id=83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab, sizeRootFs=null, sizeRw=null, imageId=sha256:4388e2379b7e870a447adbe7b80bd61f5fbf04e925832b19669fda4957f05a81, mountLabel=, name=/strange_dijkstra, restartCount=0, networkSettings=NetworkSettings(bridge=, sandboxId=, hairpinMode=false, linkLocalIPv6Address=, linkLocalIPv6PrefixLen=0, ports={}, sandboxKey=, secondaryIPAddresses=null, secondaryIPv6Addresses=null, endpointID=, gateway=, portMapping=null, globalIPv6Address=, globalIPv6PrefixLen=0, ipAddress=, ipPrefixLen=0, ipV6Gateway=, macAddress=, networks={bridge=ContainerNetwork(ipamConfig=null, links=[], aliases=null, networkID=b12d07103a9d079b360311a1add86bb3cd704fb5226248c44d9642e76a971616, endpointId=, gateway=, ipAddress=, ipPrefixLen=0, ipV6Gateway=, globalIPv6Address=, globalIPv6PrefixLen=0, macAddress=)}), path=/opt/keycloak/bin/kc.sh, processLabel=, resolvConfPath=/var/lib/docker/containers/83a9530551c80d69f8584e6c76cb63e6d53c28ccbd18fbe3eb258eccd867a4ab/resolv.conf, execIds=null, state=InspectContainerResponse.ContainerState(status=exited, running=false, paused=false, restarting=false, oomKilled=false, dead=false, pid=0, exitCode=134, error=, startedAt=2025-02-23T16:50:19.527575627Z, finishedAt=2025-02-23T16:50:19.627666086Z, health=null), volumes=null, volumesRW=null, node=null, mounts=[], graphDriver=GraphDriver(name=overlayfs, data=null), platform=linux)> within 5 seconds.
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.testcontainers.shaded.org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:691)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:708)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:458)
	... 18 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:354)
	... 20 more
Resulted in: io.vertx.core.impl.NoStackTraceException
```

**Comment by tlefevre** [comment]
Still doesn't work and the latest release, 26.1.3 still doesn't use OpenJDK 21.0.7 - can we please have a docker image with a new OpenJDK version?

**Comment by maciejlesniak** [comment]
Using environment variable `JAVA_OPTS_KC_HEAP: "-XX:UseSVE=0"` does the trick on my M4 Pro Chip.

**Comment by fbuetler** [comment]
> Still doesn't work and the latest release, 26.1.3 still doesn't use OpenJDK 21.0.7 - can we please have a docker image with a new OpenJDK version?

21.0.7 is planned to be released on [2025-04-15](https://www.java.com/releases/).

**Comment by tlefevre** [comment]
> Using environment variable `JAVA_OPTS_APPEND: "-XX:UseSVE=0"` does the trick on my M4 Pro Chip.

Yes and from what I read elsewhere, it also breaks on older Apple chips. 

Good input that 21.0.7 is not even released, I was just watching their JIRA and GitHub issues and it was resolved some time ago.

**Comment by demianjaeger-oviva** [comment]
For me the issue was also solved by updating Docker Desktop to v4.39.0.

From the [release notes](https://docs.docker.com/desktop/release-notes/#for-mac)

> Fixed a bug that caused all Java programs running on M4 Macbook Pro to emit a SIGILL error. [...]

**Comment by samreachyan** [comment]
I put the `JAVA_OPTS_APPEND` in the keycloak docker, it's working fine for M4.

```cmd
image: quay.io/keycloak/keycloak:26.1.2
    environment:
      JAVA_OPTS_APPEND: "-XX:UseSVE=0"
```

Thank resolved from https://stackoverflow.com/questions/79459633/m4-cannot-run-docker-keycloak-image

**Comment by reclaimit-ai** [comment]
For chart/operator it works by setting the `JAVA_TOOL_OPTIONS` 

### operator

```
apiVersion: apps/v1
kind: Deployment
metadata:
...
spec:
  template:
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -XX:UseSVE=0
...
```


### chart

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  unsupported:
    podTemplate:
      spec:
        containers:
          - env:
              - name: JAVA_TOOL_OPTIONS
                value: -XX:UseSVE=0
  db:
...
```

**Comment by fbuetler** [comment]
FYI yesterday, [Keycloak 21.2.1](https://github.com/keycloak/keycloak/releases/tag/26.2.1) was released, including Java 21.0.7.
