### ISSUE TITLE
[26.2.3/26.1.5] Regression: ClientList value is empty in UI for Custom UserStorageProviderFactory

### ISSUE THREAD

**Issue by prthakre** [keycloak/keycloak#38964]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

We have a custom `UserStorageProvider`, and until `26.1.4`, `ProviderConfigProperty.CLIENT_LIST_TYPE` property would show the configured value. 
However, after upgrading the instance to `26.1.5`, value shown in UI is empty. This behaviour persist in `26.2.0` as well. 
Having said that, as per` Web Developer Tools` the correct value is indeed fetched, just not shown in UI.

### Version

26.2.0, 26.1.5

### Regression

- [x] The issue is a regression

### Expected behavior

`ProviderConfigProperty.CLIENT_LIST_TYPE` should list the already configured value.

### Actual behavior

`ProviderConfigProperty.CLIENT_LIST_TYPE` property is shown as empty.

### How to Reproduce?

Create a custom UserStorageProvider with ProviderConfigProperty.CLIENT_LIST_TYPE as one of it's property.
Navigate to Storage Provider configuration page under realm->federation. Please make sure that the `client` name is such that it is not in first 20 entries of `client`. In our case it start's with `v` and is outside of 20 default fetched.

**Comment by prthakre** [comment]
This is applicable in **26.2.0** as well.

**Comment by edewit** [comment]
this might have been fixed could you try the nightly to confirm? https://github.com/keycloak/keycloak/pull/38974

**Comment by prthakre** [comment]
Afraid UI throws error (attached)
<img width="971" alt="Image" src="https://github.com/user-attachments/assets/d647747c-efd9-4bd1-810e-4f97631311d9" />

**Comment by prthakre** [comment]
@edewit Can this be back-ported to `26.1.x`?

**Comment by prthakre** [comment]
@edewit The main issue(empty `ClientList` value) still exists with `26.2.3`, though the UI exception thrown in `26.2.2` is fixed.

<img width="954" alt="Image" src="https://github.com/user-attachments/assets/91cf6591-72e0-4a74-9ed0-5343bc675512" />

**Comment by edewit** [comment]
@prthakre could you please test it on the nightly version it's fixed...

**Comment by prthakre** [comment]
@edewit sure.

**Comment by prthakre** [comment]
@edewit Just verified this with nightly build, afraid the issue persists.

<img width="1254" alt="Image" src="https://github.com/user-attachments/assets/16e2c753-5c3a-41d6-9760-7700038ca0e2" />
