### ISSUE TITLE
Vert.x thread slow / stuck

### ISSUE THREAD

**Issue by pnowy** [keycloak/keycloak#40225]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Hi, after recent update from version 26.0.7 to 26.2.4 (tried also 26.2.5) the operator started failing when keycloak manifest change.

The logs from operator:

[keycloak-logs.txt](https://github.com/user-attachments/files/20587189/keycloak-logs.txt)

Root cause:

```
1749020241203	2025-06-04 06:57:21,098 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2599 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
1749020241098
1749020241098		at java.base/java.lang.Thread.run(Thread.java:1583)
1749020241098		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
1749020241098		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
1749020241098		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
1749020241098		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
1749020241098		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658)
1749020241098		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732)
1749020241098		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:796)
1749020241098		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
1749020241098		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
1749020241098		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
1749020241098		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
1749020241098		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
1749020241098		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
1749020241098		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
1749020241098		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
1749020241098		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
1749020241098		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
1749020241098		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
1749020241098		at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1428)
1749020241098		at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1377)
1749020241098		at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1519)
1749020241098		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
1749020241097		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
1749020241097		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
1749020241097		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
1749020241097		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
1749020241097		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
1749020241097		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
1749020241097		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
1749020241097		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
1749020241097		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
1749020241097		at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
1749020241097		at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
1749020241097		at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:799)
1749020241097		at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:837)
1749020241097		at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:965)
1749020241097		at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:307)
1749020241097		at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:327)
1749020241097		at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:734)
1749020241097		at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:157)
1749020241097		at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:279)
1749020241097		at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:424)
1749020241097		at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
1749020241097		at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
1749020241097		at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
1749020241097		at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
1749020241097		at io.fabric8.kubernetes.client.vertx.VertxHttpRequest.lambda$consumeBytes$1(VertxHttpRequest.java:120)
1749020241097		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
1749020241097		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
1749020241097		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
1749020241097		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
1749020241097		at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:51)
1749020241097		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
1749020241097		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
1749020241097		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
1749020241097		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
1749020241097		at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:141)
1749020241097		at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
1749020241097		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
1749020241097		at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
1749020241097		at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:551)
1749020241097		at io.fabric8.kubernetes.client.utils.KubernetesSerialization.unmarshal(KubernetesSerialization.java:257)
1749020241097		at com.fasterxml.jackson.databind.ObjectMapper.readerFor(ObjectMapper.java:4379)
1749020241097		at com.fasterxml.jackson.databind.ObjectMapper._newReader(ObjectMapper.java:809)
1749020241097		at com.fasterxml.jackson.databind.ObjectReader.<init>(ObjectReader.java:194)
1749020241097		at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:2450)
1749020241097		at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:669)
1749020241097		at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:174)
1749020241097		at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:265)
1749020241097		at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
1749020241097		at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
1749020241097		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:990)
1749020241097		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
1749020241097		at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
1749020241097		at java.base/jdk.internal.misc.Unsafe.park(Native Method)
```

What helps is keycloak operator deployment full removal (sometimes a couple of times) and in some specific run the opertor works fine until next keycloak template diff. When this situation occur without manual intervention operator does not return to working state on his own. 

We did not register similar behavior in previous versions of operator.

### Version

26.2.4, 26.2.5

### Regression

- [x] The issue is a regression

### Expected behavior

Stable operator working.

### Actual behavior

Keycloak diff cause failing (constantly restarting) operator.

### How to Reproduce?

Install latest operator version (ie. 26.2.4, 26.2.5), generate diff on keycloak template handled by operator.

**Comment by shawkins** [comment]
Possibly relates to #39830 (which was logged against a windows environment) - @dejwsz mentions a similar situation on that issue. cc @cescoffier @vietj. Given that these issues are being reported as along with operational issues, it does seem like we are experiencing a problem beyond just a false positive blocked exception.

@pnowy if possible can you obtain a thread dump when the operator is in this state? Also can you confirm how you are deploying the operator? Are you using the base image? 

cc @ahus1 @mabartos

**Comment by pnowy** [comment]
@shawkins for deploying operator we are using official operator deployment with default operator image (`quay.io/keycloak/keycloak-operator:26.2.5`) - wrapped in helm chart due internal reasons but manifests are the same.

Regarding the thread dump - sure I can deliver that kind of dump. Do you suggest do it from within the container with `jstack`?

**Comment by shawkins** [comment]
jcmd should already be in the image and those dumps should includes virtual threads - however I don't believe that virtual threads should be coming into play with the operator just yet.

**Comment by pnowy** [comment]
@shawkins thread dumps (3 examples) from restarting pod before restart happen after initial run phase:

[keycloak-thread-dump-1.txt](https://github.com/user-attachments/files/20604882/keycloak-thread-dump-1.txt)
[keycloak-thread-dump-2.txt](https://github.com/user-attachments/files/20604881/keycloak-thread-dump-2.txt)
[keycloak-thread-dump-3.txt](https://github.com/user-attachments/files/20604880/keycloak-thread-dump-3.txt)

Hope it helps identify the issue.

**Comment by shawkins** [comment]
@pnowy can you describe the sequence more about when you took these thread dumps? Each of them appear to be during start up and do not show any vertx threads.

**Comment by pnowy** [comment]
@shawkins - yes they are done during startup on the pod before restart happen and container enter the crashloop stage (+ before that generated diff on Keycloak manifest object to make operator failing). After that I'm not able to exec into pod until next restart. If you have a recommended (better) way to handle this situation to get full thread dump I'm open to suggestion.

**Comment by shawkins** [comment]
@pnowy Is this correct?

- Operator starts successfully - is this true even if there are existing Keycloak CRs? If it comes up sucessfully evern if there are existing CRs (this means that the operator is reconciling them), can you provide more our CR spec - in particular are you using the new update strategy fields?
- Apply a diff / patch on a Keycloak CR
- The operator container will become unhealthy, then crashloop on restart - you are not able to get a threaddump once the container is unhealthy, and the pod log other than showing the vertx blocked thread does not show relevant errors / warnings

**Comment by pnowy** [comment]
@shawkins more or less it correct. But I would like describe it like this:

- (1) we have working operator and synced Keycloak CR
- (2) we change Keycloak CR (e.g. image tag as we using our own Keycloak image with metrics SPI)
- (3) Keycloak STS pods are rolled out to the new version but in the same time operator starts failing (but new CR is applied because CR become to synced, we are using ArgoCD for that kind of stuff)
- (4) to fix constantly failing operator we have to remove fully operator deployment and after second or third time the operator start working fine

The thread dump which I provided is executed between (3) and (4).

Our Keycloak CR has the following form:

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: 2
  image: our.custom.registry.keycloak:26.2.5-1
  http:
    httpEnabled: true
  hostname:
    strict: false
    strictBackchannel: false
  db:
    vendor: postgres
    usernameSecret:
      name: keycloak-db-secret
      key: POSTGRES_USERNAME
    passwordSecret:
      name: keycloak-db-secret
      key: POSTGRES_PASSWORD
    host: keycloak.xyz.rds.amazonaws.com
    database: keycloak
    port: 5432
    schema: public
  ingress:
    enabled: false
  proxy:
    headers: xforwarded
  unsupported:
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node.kubernetes.io/type
                      operator: In
                      values:
                        - infra
        tolerations:
          - effect: NoSchedule
            key: infra
            operator: Exists
```

The only non-standard stuff is affinity/tolerations but CR wasn't changed from previous version. If you need a different thread dump let me know I will try to prepare if I can.

**Comment by ahus1** [comment]
@pnowy - note that scheduling rules are now supported as part of the spec, and you don't need to put them into the `podTemplate`. See [the docs](https://www.keycloak.org/operator/advanced-configuration#_scheduling) for details. It might not solve the issue, but would move all parts of your setup to be supported.

**Comment by shawkins** [comment]
> The only non-standard stuff is affinity/tolerations but CR wasn't changed from previous version. 

Those should be fine - as @ahus1 mentions they can be moved, but that shouldn't address this issue.

The full spec helps confirms the kind of things that the operator needs to do - which in this case should be a recreate of all pods in the statefulset - scale to 0, then back up to the number of desired replicas with the new image. There was a bug with the recreate behavior in 26.2.4, but it was addressed with 26.2.5 and doesn't match the behavior you are seeing.

Can you also share the Deployment you are using for the operator - in particular cpu / memory settings?

> If you need a different thread dump let me know I will try to prepare if I can.

Ideally we need more insight into why it's becoming unstable / crashlooping. Can you try checking the kubernetes events and using --previous to see if there is anything in the older log?

There might be a way via the unsupported podTemplate to setup a preStop exec hook to take a threaddump and put it into a mount.

**Comment by pnowy** [comment]
@ahus1 - thanks for the info. We updated the spec but issue still exists.

@shawkins we have the following cpu/memory settings (used default from operator manifest):

```
resources:
  limits:
    cpu: 700m
    memory: 450Mi
  requests:
    cpu: 300m
    memory: 450Mi
```

I've updated limits to higher values but still get the logs with previously mentioned issue. Adding the logs.

[logs-2025-06-09 15_35_33.txt](https://github.com/user-attachments/files/20655660/logs-2025-06-09.15_35_33.txt)

Added also pre-hook with thread dump:

[thread-dump.txt](https://github.com/user-attachments/files/20655882/thread-dump.txt)

**Comment by shawkins** [comment]
Thank you for the updates @pnowy. I think we need further assistence from the vert.x team on this and https://github.com/keycloak/keycloak/issues/39830 - cc @vietj @cescoffier - as I don't see anything indicating a problem higher up. There's nothing about what the operator sdk / operator code is doing that would explain this behavior - startup of the operator looks normal until 2025-06-09 13:33:46,395, and we're simply waiting on IO work.

As the instance is becoming unhealthy with both the vert.x threads seeminly not making timely progress, and given this was not occurring in 26.0, marking this as a regression.

**Comment by pnowy** [comment]
@shawkins by the way - is there any idea to provide from Keycloak perspective the official Helm chart instead of operator. I'm asking because we consider a couple of times migrate from operator to just helm chart (operator in our use case is not needed after all + requires extra maintenance) but there is only up-to-date Bitnami chart which has a different environment names that official Keycloak documentation (+ non-official Keycloak image) and we haven't seen any up-to-date Keycloak helm chart.

**Comment by shawkins** [comment]
A helm chart instead of an operator? No. There is a request for using a helm chart to deploy the operator: https://github.com/keycloak/keycloak/issues/37636

**Comment by cescoffier** [comment]
Are the event loop making no progress at all (like totally blocked), or is it just slow to make progress?

Try to adjust the thread blocked time.

**Comment by shawkins** [comment]
> I've updated limits to higher values but still get the logs with previously mentioned issue.

Can you share what those are? We of course default to 450m and 700Mi and in the past tested that up to something like 100 keycloaks being managed without a problem. Can you also share how many keycloaks the operator is managing?

> Are the event loop making no progress at all (like totally blocked), or is it just slow to make progress?

@cescoffier according to the log it appears to not be making progress at all:

```
1749476040101	2025-06-09 13:34:00,100 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2395 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
1749476040099	
1749476040099		at java.base/java.lang.Thread.run(Thread.java:1583)
1749476040099		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

Then repeated every two seconds is an increment:

```
1749476042395	2025-06-09 13:34:02,394 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4793 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
1749476040103	
1749476040103		at java.base/java.lang.Thread.run(Thread.java:1583)
1749476040103		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
1749476040103		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
1749476040103		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
1749476040103		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
```

However the thread dump, which should have been taken before the process was terminated for being not ready, does show the two eventloop threads at different locations than the log. The thread dump implies the threads are sharing a trustmanagerimpl - but it's not clear becuase the ownership of the reentrant lock is not shown.

> Try to adjust the thread blocked time.

@cescoffier do you mean quarkus.vertx.max-event-loop-execute-time? https://quarkus.io/guides/all-config#quarkus-vertx_quarkus-vertx-max-event-loop-execute-time - just to clarify this should do more than just adjusting the fequency of the blocked warnings, correct?

@pnowy that would need to be set in the conf/quarkus.properties

**Comment by pnowy** [comment]
@shawkins I've set the limits to 2 CPUs and 2GB memory but I don't think this is the issue. In our case we manage only single keycloak instance that's why I've asked about official standard Keycloak Helm chart - I think in most of use-cases Helm chart is better than operator as you don't have extra layer of abstraction but as far as I know there is no official Helm chart (just Bitnami variation which is up-to-date).

**Comment by shawkins** [comment]
> I've set the limits to 2 CPUs and 2GB memory but I don't think this is the issue.

Thanks for confirming. Just wanted to make sure we capture what you have tried.

>  we change Keycloak CR (e.g. image tag as we using our own Keycloak image with metrics SPI)

Are you able to share your Dockerfile?

**Comment by pnowy** [comment]
@shawkins - sure this is our Dockerfile:

```
FROM quay.io/keycloak/keycloak:26.2.5

USER root

COPY  keycloak-metrics-spi-7.0.0.jar /opt/keycloak/providers/keycloak-metrics-spi-7.0.0.jar

USER 1000

RUN cd /opt/keycloak/bin  && \
    ./kc.sh build --db=postgres  --health-enabled=true --metrics-enabled=true --features-disabled=persistent-user-sessions
```

From our perspective we do not upgrade/modify keycloak so often and we didn't notice any operator issues where there is no keycloak manifest changes so that's not a blocker.

I believe it would be good to get some feedback from someone who manages multiple instances with operator as there that kind of issues could be more problematic to handle.

**Comment by shawkins** [comment]
Thanks for the update. The Keycloak image shouldn't be causing trouble for the operator, but I just wanted captured if possible.

> From our perspective we do not upgrade/modify keycloak so often and we didn't notice any operator issues where there is no keycloak manifest changes so that's not a blocker.

I have had no luck yet reproducing this locally on minikube - I'm creating a similar keycloak deployment, modifying the image, letting it become ready, and repeating.

Dropping to important instead of blocker based upon the initial lack of reproducability and your feedback as to the impact.

**Comment by A-Gorint** [comment]
I see that this ticket was removed from the 26.4.0 release. Do you have more info on it or when it will be investigated?

**Comment by shawkins** [comment]
> Do you have more info on it or when it will be investigated?

No, there's not much more we can do on our side. You can try following up more on https://github.com/quarkusio/quarkus/issues/48436

**Comment by mabartos** [comment]
@pnowy Is it still reproducible with the Keycloak 26.4.0? We use Quarkus 3.27 LTS, so maybe the issue is already resolved.

Please, try to reproduce it with the most recent KC release. Thanks!

**Comment by pnowy** [comment]
Hi, @mabartos we switched in the meantime to pure Keycloak Helm chart and removed operator from our workflow so unfortunately I cannot say anything if the issue still exist on latest version. We tried to upgrade with operator to 26.3.X but had still that problem and then decided to move forward without operator as in our use-case it did not provide a lot of  value for us (we don't need multiple instances and easier to track configuration/environment values than specific operator CRD settings in Keycloak documentation).

**Comment by SferaDev** [comment]
@mabartos Still seeing this on recent kernels.

Setup

```
Keycloak Operator 26.4.4
Quarkus 3.27.0
OpenJDK 17
Kernel 6.14.0-1015-aws (cgroup v2)
Container memory limit: 450Mi
```

Inside the container:

```
Max. Heap Size (Estimated): 15.41G
```

So the JVM completely ignores the cgroup memory limit and gets OOMKilled during startup.

**Comment by mabartos** [comment]
@SferaDev Thanks for the info. 

I believe it's more relevant to: https://github.com/keycloak/keycloak/issues/36609

Is that correct?
