### ISSUE TITLE
LDAP-Queries fail if previously unreachable LDAP-Server is reachable again

### ISSUE THREAD

**Issue by iceman91176** [keycloak/keycloak#43749]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

We are using user-federation with a LDAP Read-Only (Active-Directory) provider. 

* We have configured multiple domain-controllers in the connection-url to allow failover. 
* We are usiing Simpe Bind
* We are using Kerberos
* We are using LDAPS
* We are using LDAP connection pooling

The full configuration is as follows

```bash
2025-10-27 16:00:37,653 INFO  [org.keycloak.storage.ldap.LDAPIdentityStoreRegistry] (executor-thread-65) Creating new LDAP Store for the LDAP storage provider: 'mycomp Domain-Controller', LDAP Configuration: {serverPrincipal=[HTTP/auth.mycomp.services@MYCOM.NET], pagination=[true], fullSyncPeriod=[3600], startTls=[false], connectionPooling=[true], usersDn=[OU=Organisation,OU=MyComp,DC=mycomp,DC=net], cachePolicy=[DEFAULT], useKerberosForPasswordAuthentication=[false], importEnabled=[true], enabled=[true], usernameLDAPAttribute=[sAMAccountName], bindDn=[cn=ad lookup user,ou=spezial,ou=MyComp,dc=mycomp,dc=net], changedSyncPeriod=[3600], lastSync=[1761577528], vendor=[ad], uuidLDAPAttribute=[objectGUID], allowKerberosAuthentication=[true], connectionUrl=[ldaps://dc02svvc1.mycomp.net:636 ldaps://dc03svvc1.mycomp.net:636 ldaps://dc01svvc1.mycomp.net:636], syncRegistrations=[false], authType=[simple], customUserSearchFilter=[(&(objectCategory=Person)(sAMAccountName=*))], debug=[true], searchScope=[2], keyTab=[/var/run/kerberos/krb.keytab], useTruststoreSpi=[always], usePasswordModifyExtendedOp=[false], priority=[0], trustEmail=[false], kerberosRealm=[MYCOM.NET], userObjectClasses=[person, organizationalPerson, user], rdnLDAPAttribute=[cn], editMode=[READ_ONLY], validatePasswordPolicy=[false], batchSizeForSync=[1000]}, binaryAttributes: []
```

No problems occur during normal operations - even if one or two of the the LDAP-Servers go down (e.g. the first one from the list). Inm that case others LDAP-Servers are queried.

Problems arise if we shut down the first LDAP-Server and it comes back.  As soon as it is reachable again **all** LDAP-queries fail.  See below for more details.

The only ways to mitigate this issues are

* Change the order of the LDAP-Systems in the connection-url (temporary fix)
* Restart Keycloak
* Wait (probably until garbage collection has run ?)

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

If a LDAP-Server becomes available again connections should be working as expected.

### Actual behavior

As soon as the first LDAP-Server it is reachable again **all** LDAP-queries fail. 

```bash
[kc-app-01-keycloak-0 keycloak] Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@66c8b3b0
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:295)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:174)
[kc-app-01-keycloak-0 keycloak]         ... 63 more
[kc-app-01-keycloak-0 keycloak] Caused by: javax.naming.NamingException: [LDAP: error code 1 - 000004DC: LdapErr: DSID-0C090CE5, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563]; remaining name 'OU=Organisation,OU=mycomp GmbH,DC=mycomp,DC=net'
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3300)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3206)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2997)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1875)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1798)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
[kc-app-01-keycloak-0 keycloak]         at java.naming/javax.naming.directory.InitialDirContext.search(InitialDirContext.java:305)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager$3.execute(LDAPOperationManager.java:258)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager$3.execute(LDAPOperationManager.java:255)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:721)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:701)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:696)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.search(LDAPOperationManager.java:255)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:279)
[kc-app-01-keycloak-0 keycloak]         ... 64 more
```

The LDAP-error  `DSID-0C090CE5, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563]` means that an anonymous-bind is used for the query. This is strange since the the provider is configured with Simple-Bind.

### How to Reproduce?

* Configure a connection URL with at least 2 LDAP-Servers
* Shutdown the first LDAP-server
* Wait a bit
* Start the first LDAP-Server

### Anything else?

We suspect an issue with LDAP-Connection pooling that does not clean-up staly connections by default.

**Comment by pedroigor** [comment]
It might be related to https://github.com/keycloak/keycloak/issues/38660. This fix is available since `26.2.3`. Can you try using the latest version?

**Comment by iceman91176** [comment]
Thank you - we will give it a try. Unfortunately i am not able to reproduce the issue in a test-system although is has identical configuration (but not the same load). So we have to update the production-system, which needs some preparation.

**Comment by pedroigor** [comment]
It should work. Here is some logs when the first host is no longer available and the client/pool switch to the second host:

```
LdapPoolManager: using authmech: simple
com.sun.jndi.ldap.pool.Pool@5235604e {}.get(): localhost:489:::null:cn=admin,dc=keycloak,dc=org
com.sun.jndi.ldap.pool.Pool@5235604e {}.size: 0
com.sun.jndi.ldap.pool.Pool@5235604e {}.get(): creating new connections list for localhost:489:::null:cn=admin,dc=keycloak,dc=org
com.sun.jndi.ldap.pool.Connections@34743c2c.init size=1; size: 0
com.sun.jndi.ldap.pool.Connections@34743c2c.max size=300; size: 0
com.sun.jndi.ldap.pool.Pool@5235604e {}.get(): localhost:489:::null:cn=admin,dc=keycloak,dc=org
com.sun.jndi.ldap.pool.Connections@34743c2c.preferred size=0; size: 0
com.sun.jndi.ldap.pool.Pool@5235604e {localhost:489:::null:cn=admin,dc=keycloak,dc=org=com.sun.jndi.ldap.pool.ConnectionsRef@7c1ae11b}.get(): size after: 1
com.sun.jndi.ldap.pool.Pool@5235604e {localhost:489:::null:cn=admin,dc=keycloak,dc=org=com.sun.jndi.ldap.pool.ConnectionsRef@7c1ae11b}.size: 1
com.sun.jndi.ldap.pool.Pool@5235604e {localhost:489:::null:cn=admin,dc=keycloak,dc=org=com.sun.jndi.ldap.pool.ConnectionsRef@7c1ae11b}.get(): size after: 1
LdapPoolManager: using authmech: simple
com.sun.jndi.ldap.pool.Pool@5235604e {localhost:489:::null:cn=admin,dc=keycloak,dc=org=com.sun.jndi.ldap.pool.ConnectionsRef@7c1ae11b}.get(): localhost:589:::null:cn=admin,dc=keycloak,dc=org
com.sun.jndi.ldap.pool.Pool@5235604e {localhost:489:::null:cn=admin,dc=keycloak,dc=org=com.sun.jndi.ldap.pool.ConnectionsRef@7c1ae11b}.size: 1
com.sun.jndi.ldap.pool.Pool@5235604e {localhost:489:::null:cn=admin,dc=keycloak,dc=org=com.sun.jndi.ldap.pool.ConnectionsRef@7c1ae11b}.get(): creating new connections list for localhost:589:::null:cn=admin,dc=keycloak,dc=org
```

**Comment by iceman91176** [comment]
@pedroigor - the issue is still there after upgrading to keycloak 26.3.3.  
Same behaviour - if the first LDAP-Server is reachable again all LDAP-Queries fail

`
[kc-app-01-keycloak-0 keycloak] 2025-12-09 10:59:51,923 ERROR [org.keycloak.authorization.authorization.AuthorizationTokenService] (executor-thread-9016) Unexpected error while evaluating permissions: java.lang.RuntimeException: Failed to evaluate permissions
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.policy.evaluation.DecisionPermissionCollector.onError(DecisionPermissionCollector.java:189)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.permission.evaluator.UnboundedPermissionEvaluator.evaluate(UnboundedPermissionEvaluator.java:53)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.permission.evaluator.UnboundedPermissionEvaluator.evaluate(UnboundedPermissionEvaluator.java:65)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.authorization.AuthorizationTokenService.evaluateAllPermissions(AuthorizationTokenService.java:305)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.authorization.AuthorizationTokenService.authorize(AuthorizationTokenService.java:225)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.protocol.oidc.grants.PermissionGrantType.process(PermissionGrantType.java:187)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:151)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_3903cccf0670c489ab77dc2ba1ba757573ec6d78.invoke(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
[kc-app-01-keycloak-0 keycloak]         at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
[kc-app-01-keycloak-0 keycloak]         at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
[kc-app-01-keycloak-0 keycloak]         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:638)
[kc-app-01-keycloak-0 keycloak]         at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
[kc-app-01-keycloak-0 keycloak]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
[kc-app-01-keycloak-0 keycloak]         at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
[kc-app-01-keycloak-0 keycloak]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
[kc-app-01-keycloak-0 keycloak]         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
[kc-app-01-keycloak-0 keycloak]         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
[kc-app-01-keycloak-0 keycloak]         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.lang.Thread.run(Unknown Source)
[kc-app-01-keycloak-0 keycloak] Caused by: org.keycloak.models.ModelException: Failed to fetch results from the LDAP [mycomp Domain-Controller] provider
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:178)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getFirstResult(LDAPQuery.java:185)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.LDAPStorageProvider.loadLDAPUserByUsername(LDAPStorageProvider.java:1053)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.LDAPStorageProvider.getUserByUsername(LDAPStorageProvider.java:656)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.UserStorageManager.lambda$getUserByUsername$20(UserStorageManager.java:472)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.utils.ServicesUtils.lambda$timeBoundOne$1(ServicesUtils.java:83)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.UserStorageManager.tryResolveFederatedUser(UserStorageManager.java:1054)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.UserStorageManager.getUserByAttribute(UserStorageManager.java:1049)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.UserStorageManager.getUserByUsername(UserStorageManager.java:471)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByUsername(UserCacheSession.java:279)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.policy.evaluation.DefaultEvaluation$1.getUser(DefaultEvaluation.java:188)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.policy.evaluation.DefaultEvaluation$1.getUserGroups(DefaultEvaluation.java:272)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.policy.provider.group.GroupPolicyProvider.evaluate(GroupPolicyProvider.java:66)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.policy.provider.permission.AbstractPermissionProvider.evaluate(AbstractPermissionProvider.java:62)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.policy.provider.permission.ResourcePolicyProvider.evaluate(ResourcePolicyProvider.java:50)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.lambda$createPolicyEvaluator$0(DefaultPolicyEvaluator.java:142)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.cacheQuery(StoreFactoryCacheSession.java:1087)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.cacheQuery(StoreFactoryCacheSession.java:1062)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.findByResource(StoreFactoryCacheSession.java:948)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.AuthorizationProvider$3.findByResource(AuthorizationProvider.java:412)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.evaluateResourcePolicies(DefaultPolicyEvaluator.java:92)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.evaluate(DefaultPolicyEvaluator.java:71)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.permission.evaluator.UnboundedPermissionEvaluator.lambda$evaluate$0(UnboundedPermissionEvaluator.java:49)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.permission.Permissions.lambda$all$0(Permissions.java:78)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$ResourceCache.cacheQuery(StoreFactoryCacheSession.java:828)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$ResourceCache.cacheQuery(StoreFactoryCacheSession.java:800)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$ResourceCache.findByOwner(StoreFactoryCacheSession.java:668)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.AuthorizationProvider$4.findByOwner(AuthorizationProvider.java:514)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.permission.Permissions.all(Permissions.java:76)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.authorization.permission.evaluator.UnboundedPermissionEvaluator.evaluate(UnboundedPermissionEvaluator.java:48)
[kc-app-01-keycloak-0 keycloak]         ... 18 more
[kc-app-01-keycloak-0 keycloak] Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@3df31d2a
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:294)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:174)
[kc-app-01-keycloak-0 keycloak]         ... 68 more
[kc-app-01-keycloak-0 keycloak] Caused by: javax.naming.NamingException: [LDAP: error code 1 - 000004DC: LdapErr: DSID-0C090CE5, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563]; remaining name 'OU=Organisation,OU=mycomp GmbH,DC=mycomp,DC=net'
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.searchAux(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.c_search(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/javax.naming.directory.InitialDirContext.search(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager$3.execute(LDAPOperationManager.java:259)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager$3.execute(LDAPOperationManager.java:256)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:742)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:714)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:709)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.search(LDAPOperationManager.java:256)
[kc-app-01-keycloak-0 keycloak]         at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:278)
[kc-app-01-keycloak-0 keycloak]         ... 69 more
[kc-app-01-keycloak-0 keycloak]
[kc-app-01-keycloak-0 keycloak] 2025-12-09 10:59:51,924 ERROR [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager] (executor-thread-9015) Could not query server using DN [OU=Organisation,OU=mycomp GmbH,DC=mycomp,DC=net] and filter [(&(&(objectCategory=Person)(sAMAccountName=*))(mail=e0089304-0a64-4592-8532-18f8ab7ed870)(objectclass=person)(objectclass=organizationalPerson)(objectclass=user))]: javax.naming.NamingException: [LDAP: error code 1 - 000004DC: LdapErr: DSID-0C090CE5, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563]; remaining name 'OU=Organisation,OU=mycomp GmbH,DC=mycomp,DC=net'
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.searchAux(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.ldap.LdapCtx.c_search(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(Unknown Source)
[kc-app-01-keycloak-0 keycloak]         at java.naming/javax.naming.directory.InitialDirContext.search(Unknown Source)
`

**Comment by iceman91176** [comment]
In we disable Connection-Pooling for the LDAP-Provider, we get the mentioned errors, too - but only a few for a very short time. After a couple of seconds everything works as expected again.

It seems like keycloak is using anonymous-binds on re-connects  ? At least this is what what the DSID-0C090CE5 error suggests. In case of a connection pool it does it over and over again (until the entries are evicted). Without connection pool an authenticated bind is performed almost immediately after the failure.
